<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Загрузка фото новой обуви</h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <p>Drag multiple files to the box below for multi upload or click to select files. This is for demonstration purposes only, the files are not uploaded to any server.</p>
            <form style="border: 1px solid #e5e5e5; height: 300px; " class="dropzone dz-clickable" action="/admin/shoes/blank">
                <div class="dz-default dz-message"><span>Drop files here to upload</span></div></form>

            <br>
            <br>
            <br>
            <br>
        </div>
    </div>
</div>
