<form class="form-horizontal form-label-left" method="post" action="/admin/shoes/save">

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Обувь</small></h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <?php $this->partial("partials/messages"); ?>
            <br>
                <?php echo $form->render("id"); ?>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Название</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        <?php echo $form->render("name", array('class' => 'form-control')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Цена</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        <?php echo $form->render("price", array('class' => 'form-control')); ?>
                    </div>
                </div>


                <div class="ln_solid"></div>
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Описание</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        <textarea name="description" id="description" ><?=$shoes->description ? $shoes->description->description : ''?></textarea>
                        <br>
                    </div>
                </div>
                <?php $groups = \Models\AttributesGroups::find()?>
                <?php foreach($groups as $group):?>
                <div class="ln_solid"></div>
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">
                        <?=$group->name?>
                    </label>

                    <div class="col-md-9 col-sm-9 col-xs-12">
                        <?php foreach($group->attributes as $attribute):?>
                            <?php $checked = $shoes->hasAttribute($attribute)?>
                        <div class="checkbox">
                            <label class="">
                                <div class="icheckbox_flat-green <?=$checked ? 'checked' : ''?>" style="position: relative;">
                                    <input type="checkbox" name="attributes[<?=$attribute->id?>]" value="1" class="flat" <?=$checked ? 'checked="checked"' : ''?> style="position: absolute; opacity: 0;">
                                    <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);"></ins>
                                </div> <?=$attribute->name?>
                            </label>
                        </div>
                        <?php endforeach?>
                    </div>
                </div>
                <?php endforeach?>
        </div>
    </div>
</div>

<?php if($shoes->id):?>

    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Изображения</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <div class="row">
                    <?php foreach($shoes->images as $image):?>
                    <div class="col-md-55">
                        <div class="thumbnail">
                            <div class=" view view-first">
                                <img alt="image" src="<?=$image->thumbnailURL(125, 125)?>" width="200px" style="width: 100%; display: block;">
                            </div>
                        </div>
                        <div class="radio">
                            <label class="">
                                <?php $is_checked = $image->id == $shoes->main_image_id?>
                                <div class="iradio_flat-green <?=$is_checked ? 'checked' : ''?>" style="position: relative;">
                                    <input type="radio" class="flat" <?=$is_checked ? 'checked=""' : ''?> name="main_image_id" value="<?=$image->id?>" style="position: absolute; opacity: 0;">
                                    <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);"></ins>
                                </div> Выбрать главной
                            </label>
                        </div>
                        <div class="radio">
                            <a href="/admin/shoes_images/delete/<?=$image->id?>" onclick="return confirm('Удалить?');">Удалить</a>
                        </div>
                    </div>
                    <?php endforeach?>

                </div>

            </div>
        </div>
    </div>

    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_content">
                <div class="form-group">
                    <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                        <button class="btn btn-success" type="submit" id="button-save">Сохранить</button>
                        <button class="btn btn-primary" type="submit" onclick="location='/admin/shoes/index'; return false;">Список</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

</form>

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Загрузка фото новой обуви</h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <p>Drag multiple files to the box below for multi upload or click to select files. This is for demonstration purposes only, the files are not uploaded to any server.</p>
            <form style="border: 1px solid #e5e5e5; height: 300px; " class="dropzone dz-clickable" action="/admin/shoes/image/<?=$shoes->id?>">
                <div class="dz-default dz-message"><span>Drop files here to upload</span></div></form>

            <br>
            <br>
            <br>
            <br>
        </div>
    </div>
</div>
<?php endif?>
