

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Обувь</small></h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <?php $this->partial("partials/messages"); ?>
            <br>
            <form class="form-horizontal form-label-left" method="post" action="/admin/shoes/save">
                <?php echo $form->render("id"); ?>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Название</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        <?php echo $form->render("name", array('class' => 'form-control')); ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Артикул</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        <?php echo $form->render("article", array('class' => 'form-control')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Цена</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        <?php echo $form->render("price", array('class' => 'form-control')); ?>
                    </div>
                </div>

                <div class="ln_solid"></div>
                <div class="form-group">
                    <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                        <button class="btn btn-primary" type="submit">Отмена</button>
                        <button class="btn btn-success" type="submit">Сохранить</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>

<?php if($shoes->id):?>

    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Изображения</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <div class="row">
                    <?php foreach($shoes->shoesImages as $image):?>
                    <div class="col-md-55">
                        <div class="thumbnail">
                            <div class="image view view-first">
                                <?=$image->id?>
                                <img alt="image" src="<?=$image->originalPath()?>" width="200px" style="width: 100%; display: block;">
                            </div>
                           
                        </div>
                    </div>
                    <?php endforeach?>

                </div>

            </div>
        </div>
    </div>


<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Загрузка фото новой обуви</h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <p>Drag multiple files to the box below for multi upload or click to select files. This is for demonstration purposes only, the files are not uploaded to any server.</p>
            <form style="border: 1px solid #e5e5e5; height: 300px; " class="dropzone dz-clickable" action="/admin/shoes/image/<?=$shoes->id?>">
                <div class="dz-default dz-message"><span>Drop files here to upload</span></div></form>

            <br>
            <br>
            <br>
            <br>
        </div>
    </div>
</div>
<?php endif?>