<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Обувь</small></h2>
            <div class="clearfix"></div>
        </div>

        <div class="x_content">

            <table class="table table-striped responsive-utilities jambo_table bulk_action shoes-list">
                <thead>
                <tr class="headings">
                    <th class="column-title">ID</th>
                    <th class="column-title">Название </th>
                    <th class="column-title">Изображения </th>
                    <th class="column-title">Артикул</th>
                    <th class="column-title">Цена</th>
                    <th class="column-title">&nbsp;</th>
                </tr>
                </thead>

                <tbody>
                <?php foreach($shoes as $s):?>
                <tr class="even pointer" data-shoes-id="<?=$s->id?>">
                    <td class=" "><?=$s->id?></td>
                    <td class=" "><?=$s->name.($shoes->is_hidden ? ' (скрытый)' : '')?></td>
                    <td class=" ">
                        <?php foreach($s->images as $image):?>
                            <a target="_blank" href="<?=$image->originalURL()?>"></a><img alt="image" src="<?=$image->thumbnailURL(85, 85)?>" /></a>
                        <?php endforeach?>
                    </td>
                    <td class=" "><?=$s->article?></td>
                    <td class=" "><?=$s->price?></td>
                    <td class=" last">
                        <a href="/admin/shoes/edit/<?=$s->id?>">Редактировать</a>
                        <a href="/admin/shoes/delete/<?=$s->id?>" onclick="return confirm('Удалить \'<?=$s->name?>\'?');">Удалить</a>
                    </td>
                </tr>
                <?php endforeach?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">
    $("table.shoes-list tbody").sortable({
        items: "> tr",
        appendTo: "parent",
        helper: "clone",
        start: function(event, ui) {
            // get row number, such as (row) 1
        },
        stop: function(ui, event){debugger
            var index = event.item.index();
            var shoes_id=event.item.data('shoes-id');

            $.get( "/admin/shoes/order?id=" + shoes_id + "&index=" + index, function( data ) {

            });
        }
    }).disableSelection();
</script>