<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Обувь</small></h2>
            <div class="clearfix"></div>
        </div>

        <div class="x_content">

            <table class="table table-striped responsive-utilities jambo_table bulk_action">
                <thead>
                <tr class="headings">
                    <th class="column-title">Название </th>
                    <th class="column-title">Изображения </th>
                    <th class="column-title">Артикул</th>
                    <th class="column-title">Цена</th>
                    <th class="column-title">&nbsp;</th>
                </tr>
                </thead>

                <tbody>
                <?php foreach($shoes as $s):?>
                <tr class="even pointer">
                    <td class=" "><?=$s->name?></td>
                    <td class=" ">
                        <?php foreach($s->shoesImages as $image):?>
                            <img alt="image" src="<?=$image->thumbnailURL(85, 85)?>" />
                        <?php endforeach?>
                    </td>
                    <td class=" "><?=$s->article?></td>
                    <td class=" "><?=$s->price?></td>
                    <td class=" last">
                        <a href="/admin/shoes/edit/<?=$s->id?>">Редактировать</a>
                        <a href="/admin/shoes/delete/<?=$s->id?>" onclick="return confirm('Удалить \'<?=$s->name?>\'?');">Удалить</a>
                    </td>
                </tr>
                <?php endforeach?>
                </tbody>
            </table>
        </div>
    </div>
</div>