<!doctype html>
<!--[if lt IE 8]><html class="no-js ie7" lang="en"> <![endif]-->
<!--[if IE 8]><html class="no-js ie8" lang="en"> <![endif]-->
<!--[if (gt IE 8)|!(IE)]><!--> <html class="no-js"> <!--<![endif]-->
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">


    <title>RUMI</title>

    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" media="all" />
    <link href="/redesign/css/main.css" rel="stylesheet" type="text/css" media="all" />

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js" type="text/javascript"></script>
    <link href="//fonts.googleapis.com/css?family=Montserrat:400,400italic,500,600,700,700italic" rel="stylesheet" type="text/css">
    <link href="//fonts.googleapis.com/css?family=Raleway:400,400italic,500,600,700,700italic" rel="stylesheet" type="text/css">
    <link href="//fonts.googleapis.com/css?family=Arvo:400,400italic,700" rel="stylesheet" type="text/css">


    <!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!--[if lt IE 10]>
    <script src="/redesign/js/js_placeholder.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        jQuery(document).ready(function(){
            $('input, textarea').placeholder();
        });
    </script>
    <![endif]-->

</head>

<body id="king" class="template-index no-touch clearfix">

<div id="shopify-section-sidebar" class="shopify-section mount-sidebar mount-overlay">
    <div id="sidebar-holder">
        <div id="sidebar">
            <div style="flex: 1 0 auto;">
                <header id="logo">
                    <h1 itemscope itemtype="//schema.org/Organization">
                        <a class="logo-img" href="/" itemprop="url">
                            <img src="/redesign/img/logo.png" alt="RUMI" style="max-width: 110px;" />
                        </a>
                    </h1>
                </header>

                <?php $this->partial("partials/meta"); ?>
                <?php $this->partial("partials/menu"); ?>
            </div>
            <?php $this->partial("partials/footer"); ?>
        </div>
    </div>
</div>

<div id="content-holder">

    <main id="content" role="main">

        <div id="page-content">
            <?php echo $this->getContent(); ?>
        </div>
    </main>
</div>


<script type="text/javascript">

    // Saving theme settings and local translations as global variables

    jQuery.themeSettings = {
        cart_action: "overlay"
    }

    jQuery.themeWords = {
        products_page_share_text: "Spread the word",
        products_page_more_description_label: "Show more",
        products_page_less_description_label: "Show less"
    }





    jQuery.themeAssets = {
        arrowLeft: '<svg version="1.1" class="svg left" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="60px" height="60px" viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve"><g><path d="M24.294,33.641c-0.908-0.991-1.694-1.745-2.357-2.261c-0.663-0.517-1.289-0.901-1.877-1.154v-0.461c0.677-0.329,1.333-0.748,1.969-1.256c0.635-0.51,1.395-1.257,2.276-2.242h0.79c-0.643,1.375-1.316,2.431-2.021,3.169l16.355,0v1.036l-16.355,0c0.52,0.657,0.882,1.147,1.086,1.471c0.206,0.325,0.51,0.891,0.912,1.697H24.294z"/></g></svg>',
        arrowRight: '<svg version="1.1" class="svg right" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="60px" height="60px" viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve"><g><path d="M35.195,26.268c0.908,0.991,1.694,1.745,2.357,2.261c0.663,0.517,1.289,0.901,1.877,1.154v0.461c-0.677,0.328-1.333,0.747-1.969,1.256c-0.636,0.51-1.395,1.257-2.276,2.241h-0.79c0.643-1.375,1.316-2.431,2.021-3.169H20.06v-1.036h16.355c-0.52-0.656-0.882-1.146-1.087-1.471s-0.51-0.891-0.912-1.697H35.195z"/></g></svg>',
        arrowDown: '<svg version="1.0" class="svg arrow" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="7px" height="4px" viewBox="0 0 7 4" enable-background="new 0 0 7 4" xml:space="preserve"><polygon points="7.006,-0.044 3.5,3.961 -0.006,-0.044 "/></svg>',
        mgnpop: "//cdn.shopify.com/s/files/1/0691/8855/t/14/assets/js_magnific.popup.min.js?5446409592219251106"
    }

</script>

<script src="/redesign/js/js_plugins.min.js" type="text/javascript"></script>
<script src="/redesign/js/js_scripts.min.js" type="text/javascript"></script>

</body>
</html>