<!doctype html>
<!--[if lt IE 8]><html class="no-js ie7" lang="en"> <![endif]-->
<!--[if IE 8]><html class="no-js ie8" lang="en"> <![endif]-->
<!--[if (gt IE 8)|!(IE)]><!--> <html class="no-js"> <!--<![endif]-->
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">


    <title>RUMI</title>

    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" media="all" />
    <link href="//cdn.shopify.com/s/files/1/0691/8855/t/14/assets/css_main.scss.css?5446409592219251106" rel="stylesheet" type="text/css" media="all" />

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js" type="text/javascript"></script>
    <link href="//fonts.googleapis.com/css?family=Montserrat:400,400italic,500,600,700,700italic" rel="stylesheet" type="text/css">
    <link href="//fonts.googleapis.com/css?family=Raleway:400,400italic,500,600,700,700italic" rel="stylesheet" type="text/css">
    <link href="//fonts.googleapis.com/css?family=Arvo:400,400italic,700" rel="stylesheet" type="text/css">


    <!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <link href="//cdn.shopify.com/s/files/1/0691/8855/t/14/assets/respond-proxy.html" id="respond-proxy" rel="respond-proxy" />
    <link href="//king-theme.myshopify.com/search?q=7e3fc9c53b3690194df932304a8d756f" id="respond-redirect" rel="respond-redirect" />
    <script src="//king-theme.myshopify.com/search?q=7e3fc9c53b3690194df932304a8d756f" type="text/javascript"></script>
    <![endif]-->

    <!--[if lt IE 10]>
    <script src="//cdn.shopify.com/s/files/1/0691/8855/t/14/assets/js_placeholder.min.js?5446409592219251106" type="text/javascript"></script>
    <script type="text/javascript">
        jQuery(document).ready(function(){
            $('input, textarea').placeholder();
        });
    </script>
    <![endif]-->

</head>

<body id="king" class="template-index no-touch clearfix">

<div id="shopify-section-sidebar" class="shopify-section mount-sidebar mount-overlay">
    <div id="sidebar-holder">
        <div id="sidebar">
            <div style="flex: 1 0 auto;">
                <header id="logo">
                    <h1 itemscope itemtype="//schema.org/Organization">
                        <a class="logo-img" href="/" itemprop="url">
                            <img src="//cdn.shopify.com/s/files/1/0691/8855/files/logo_x2.png?v=1484911064" alt="King " style="max-width: 110px;" />
                        </a>
                    </h1>
                </header>

                <?php $this->partial("partials/meta"); ?>
                <?php $this->partial("partials/menu"); ?>
            </div>
            <?php $this->partial("partials/footer"); ?>
        </div>
    </div>
</div>

<div id="content-holder">

    <main id="content" role="main">

        <div id="page-content">
            <?php echo $this->getContent(); ?>
        </div>
    </main>
</div>

<div id="main-overlay">

    <div id="search-overlay" class="table-display">
        <div>
            <div class="simple-overlay-box">

                <h5>Search the store</h5>




                <form action="/search" method="get" class="input-group search-bar" role="search">
                    <input type="search" name="q" value="" placeholder=" Type keyword and hit enter ">
                    <!-- <input type="hidden" name="type" value="product" /> -->
                    <button type="submit">

                        <svg version="1.1" class="svg search" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="100px" height="100px" viewBox="0 0 100 100" enable-background="new 0 0 100 100" xml:space="preserve"><g><g><path d="M91.473,78.791L75.877,63.193c4.237-6.103,6.729-13.512,6.729-21.49c0-20.844-16.963-37.799-37.806-37.799C23.956,3.904,7,20.859,7,41.703c0,20.849,16.956,37.803,37.8,37.803c5.744,0,11.189-1.29,16.069-3.593l16.742,16.744c1.805,1.799,4.214,2.79,6.777,2.79c2.627,0,5.105-1.032,6.979-2.901C95.188,88.725,95.234,82.55,91.473,78.791z M22.119,41.703c0-12.505,10.176-22.682,22.681-22.682c12.507,0,22.683,10.177,22.683,22.682c0,12.509-10.176,22.686-22.683,22.686C32.295,64.389,22.119,54.212,22.119,41.703z"/></g></g></svg>
                    </button>
                </form>
                <a href="#" class="close main">

                    <svg version="1.1" class="svg close" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="60px" height="60px" viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve"><polygon points="38.936,23.561 36.814,21.439 30.562,27.691 24.311,21.439 22.189,23.561 28.441,29.812   22.189,36.064 24.311,38.186 30.562,31.934 36.814,38.186 38.936,36.064 32.684,29.812 "/></svg>
                </a>

            </div>
        </div>
    </div>







    <div id="share-overlay" class="table-display">
        <div>
            <div class="simple-overlay-box">

                <h5>Spread the word</h5>


                <a class="share-on-facebook" target="_blank" href="//www.facebook.com/sharer.php?u="><i class="fa fa-fw fa-facebook"></i></a>
                <a class="share-on-twitter" target="_blank" href="//twitter.com/share?text=&amp;url="><i class="fa fa-fw fa-twitter"></i></a>
                <a class="share-on-google" target="_blank" href="//plus.google.com/share?url="><i class="fa fa-fw fa-google-plus"></i></a>
                <a class="share-on-pinterest" target="_blank" href="http://pinterest.com/pin/create/button/?url=&amp;media=&amp;description="><i class="fa fa-fw fa-pinterest"></i></a>
                <!-- <a class="share-on-mail" target="_blank" href="mailto:youremail@domain.com?subject=Look what i've found&amp;body=Check out : "><i class="fa fa-fw fa-mail"></i></a> -->
                <a href="#" class="close main">

                    <svg version="1.1" class="svg close" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="60px" height="60px" viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve"><polygon points="38.936,23.561 36.814,21.439 30.562,27.691 24.311,21.439 22.189,23.561 28.441,29.812   22.189,36.064 24.311,38.186 30.562,31.934 36.814,38.186 38.936,36.064 32.684,29.812 "/></svg>
                </a>

            </div>
        </div>
    </div>

    <div id="shopify-section-popup" class="shopify-section newsletter-section table-display"><div>

            <style type="text/css">
                #newsletter-box:before {
                    background-image: url(//cdn.shopify.com/s/files/1/0691/8855/files/newsletter_900x.jpg?v=1484911334);
                }
            </style>

            <div id="newsletter-box" class="clearfix" data-newsletter_check="true" data-newsletter_auto="30" data-newsletter_mobile="false" data-newsletter_confirm="Thanks for subscribing!">

                <h5>King Newsletter</h5>
                <div id="newsletter-text" class="rte"><p>Stay up to date on the latest product releases, special offers &amp; news by signing up for our newsletter.</p></div>



                <form method="post" action="https://king-theme.myshopify.com/contact#contact_form" id="contact_form" class="contact-form" accept-charset="UTF-8"><input type="hidden" value="customer" name="form_type" /><input type="hidden" name="utf8" value="✓" />

                    <div class="input-group">
                        <input type="hidden" name="contact[tags]" value="newsletter">
                        <input type="email" value="" placeholder="Email Address" name="contact[email]" id="Email" aria-label="Email Address" autocorrect="off" autocapitalize="off">
                        <input type="submit" name="commit" id="Subscribe" value="Submit">
                    </div>
                </form>

                <a href="#" class="close main">

                    <svg version="1.1" class="svg close" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="60px" height="60px" viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve"><polygon points="38.936,23.561 36.814,21.439 30.562,27.691 24.311,21.439 22.189,23.561 28.441,29.812   22.189,36.064 24.311,38.186 30.562,31.934 36.814,38.186 38.936,36.064 32.684,29.812 "/></svg>
                </a>

            </div>

        </div>

    </div>

</div>

<script type="text/javascript">

    // Saving theme settings and local translations as global variables

    jQuery.themeSettings = {
        cart_action: "overlay"
    }

    jQuery.themeWords = {
        products_page_share_text: "Spread the word",
        products_page_more_description_label: "Show more",
        products_page_less_description_label: "Show less"
    }





    jQuery.themeAssets = {
        arrowLeft: '<svg version="1.1" class="svg left" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="60px" height="60px" viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve"><g><path d="M24.294,33.641c-0.908-0.991-1.694-1.745-2.357-2.261c-0.663-0.517-1.289-0.901-1.877-1.154v-0.461c0.677-0.329,1.333-0.748,1.969-1.256c0.635-0.51,1.395-1.257,2.276-2.242h0.79c-0.643,1.375-1.316,2.431-2.021,3.169l16.355,0v1.036l-16.355,0c0.52,0.657,0.882,1.147,1.086,1.471c0.206,0.325,0.51,0.891,0.912,1.697H24.294z"/></g></svg>',
        arrowRight: '<svg version="1.1" class="svg right" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="60px" height="60px" viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve"><g><path d="M35.195,26.268c0.908,0.991,1.694,1.745,2.357,2.261c0.663,0.517,1.289,0.901,1.877,1.154v0.461c-0.677,0.328-1.333,0.747-1.969,1.256c-0.636,0.51-1.395,1.257-2.276,2.241h-0.79c0.643-1.375,1.316-2.431,2.021-3.169H20.06v-1.036h16.355c-0.52-0.656-0.882-1.146-1.087-1.471s-0.51-0.891-0.912-1.697H35.195z"/></g></svg>',
        arrowDown: '<svg version="1.0" class="svg arrow" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="7px" height="4px" viewBox="0 0 7 4" enable-background="new 0 0 7 4" xml:space="preserve"><polygon points="7.006,-0.044 3.5,3.961 -0.006,-0.044 "/></svg>',
        mgnpop: "//cdn.shopify.com/s/files/1/0691/8855/t/14/assets/js_magnific.popup.min.js?5446409592219251106"
    }

</script>

<script src="//cdn.shopify.com/s/files/1/0691/8855/t/14/assets/js_plugins.min.js?5446409592219251106" type="text/javascript"></script>
<script src="//cdn.shopify.com/s/files/1/0691/8855/t/14/assets/js_scripts.min.js?5446409592219251106" type="text/javascript"></script>

</body>
</html>