<?php $class = array('error' => 'alert-danger', 'success' => 'alert-success', 'notice' => 'alert-info', 'warning' => 'alert-warning');
var_dump($this->flashSession->getMessages());
?>
    <?php foreach((array) $this->flashSession->getMessages() as $type => $messages):?>
        <?php if(empty($messages)) {continue; }?>
        <?php foreach($messages as $message):?>
        <div role="alert" class="alert <?=$class[$type]?> alert-dismissible fade in">
            <button aria-label="Close" data-dismiss="alert" class="close" type="button"><span aria-hidden="true">×</span>
            </button>
            <?=$message?>
        </div>
    <?php endforeach?>
<?php endforeach?>