<div class="popular-tab-product featured-product-area">
    <?php foreach($promo->shoes as $shoes):?>
    <div class="col-xs-12 col-sm-3">
        <div class="featured-inner">
            <div class="featured-image">
                <a href="<?=$shoes->getURL()?>">
                    <img src="<?=$shoes->mainImage->thumbnailURL(250, 250)?>" alt="">
                </a>
            </div>
            <div class="featured-info">
                <a href="<?=$shoes->getURL()?>"><?=$shoes->name?></a>
                <span class="price"><?=$shoes->price?></span>
                <div class="featured-button">
                    <a class="add-to-card" data-shoes-id="<?=$shoes->id?>"><i class="fa fa-shopping-cart"></i>Купить</a>
                </div>
            </div>
        </div>
    </div>
    <?php endforeach?>
</div>