<div class="page-content">
    <!-- Start breadcume area -->
    <div class="breadcume-area">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="breadcrumb">
                        <a title="Новинки" href="/" class="home"><i class="fa fa-home"></i></a>
                        <span class="navigation-pipe">&gt;</span>
                        Контакты
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End breadcume area -->
    <!-- Start contact page area -->
    <div class="container">
        <!-- Start contact-map -->
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <h4 class="cart-title">Контакты</h4>
                <div class="contact-map">
                    <div id="googleMap" style="position: relative; overflow: hidden; transform: translateZ(0px); background-color: rgb(229, 227, 223);">
                    </div>
                </div>
<br />
<br />
<br />
                <div id="street-view" style="width: 100%;height: 600px;">

                </div>
            </div>
        </div>
        <!-- End contact-map -->
        <!-- Start contact from atea -->
        <div class="contact-from-atea">
            <div class="form-and-info">
                <div class="row">
                    <div class="col-xs-12 col-sm-4 col-md-4">
                        <div class="contactDetails contactHead">
                            <h3>Связаться с нами</h3>
                            <p>
                                <span class="iconContact"><i class="fa fa-map-marker"></i></span>
                                &nbsp;
                            </p>
                            <p>
                                <span class="iconContact"><i class="fa fa-phone"></i></span>
                                Телефон: (050) 985-11-00 <br> Viber: (098) 098-21-37
                            </p>
                            <p>
                                <span class="iconContact"><i class="fa fa-envelope-o"></i></span>
                                Email: rumi.shoes@gmail.com <br>
                            </p>
                        </div>
                        <!--div class="social-area contactHead">
                            <h3>Flowe us</h3>
                            <ul class="socila-icon">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-rss"></i></a></li>
                                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            </ul>
                        </div-->
                    </div>
                    <div class="col-xs-12 col-sm-8 col-md-8">
                        <div class="contactfrom">
                            <h3>Сообщение</h3>
                            <form class="" method="post">
                                <div class="row">
                                    <div class="col-md-6">
                                        <input type="text" placeholder="Имя" name="name" class="form-control">
                                    </div>
                                    <div class="col-md-6 contactemail">
                                        <input type="text" placeholder="Email" name="email" class="form-control">
                                    </div>
                                    <div class="col-md-12">
                                        <textarea name="message" placeholder="Текст сообщения" rows="13" class="form-control"></textarea>
                                    </div>
                                </div>
                                <button class="btn btnContact" type="submit">Отправить сообщение</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End contact from atea -->
    </div>
</div>


<!-- Google Map js -->
<script src="https://maps.googleapis.com/maps/api/js"></script>
<script>
    function initialize() {
        var mapOptions = {
            zoom: 15,
            scrollwheel: false,
            center: new google.maps.LatLng(48.4984629, 35.0629983)
        };

        var map = new google.maps.Map(document.getElementById('googleMap'),
            mapOptions);


        var marker = new google.maps.Marker({
            position: map.getCenter(),
            animation:google.maps.Animation.BOUNCE,
            icon: '/img/map-marker.png',
            map: map
        });

    }

    google.maps.event.addDomListener(window, 'load', initialize);
</script>


<script>
    var panorama;
    function initialize() {
        panorama = new google.maps.StreetViewPanorama(
            document.getElementById('street-view'),
            {
                position: {lat: 48.4984629, lng: 35.0629983},
                pov: {heading: 165, pitch: 0},
                zoom: 1
            });
    }
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCeK_IwArHdpM9bjPjRKbOYIDLkyKQ0c0k&callback=initialize">
</script>
