<div id="shopify-section-slideshow" class="shopify-section">

    <div id="home-slider" class="swiper-container" data-section-id="slideshow" data-transition="slide" data-autoplay="true" data-timer="7">

        <div class="swiper-wrapper">



            <div class="slide swiper-slide slide--1484211369679"  data-index="1">
                <?php $slide = \Models\Shoes::findFirst(140)?>
                <?php if($slide):?>

                <div class="slide-img image" style="background-image:url(<?=$slide->MainImage->originalURL()?>)">



                    <img src="<?=$slide->MainImage->originalURL()?> " alt="" />

                    <div class="slide-caption right light">
                        <div class="table-display">
                            <div>
                                <a class="button dark label d" href="<?=$slide->getURL()?>">Купить<span>&rarr;</span></a>


                            </div>
                        </div>
                    </div>

                </div>
              <?php endif?>



            </div>



            <div class="slide swiper-slide slide--1484211385979"  data-index="2">
                <?php $slide = \Models\Shoes::findFirst(141)?>
                <?php if($slide):?>

                <div class="slide-img image" style="background-image:url(<?=$slide->MainImage->originalURL()?>)">



                    <img src="<?=$slide->MainImage->originalURL()?>" alt="" />

                    <div class="slide-caption right light">
                        <div class="table-display">
                            <div>


                                <a class="button dark label d" href="<?=$slide->getURL()?>">Купить<span>&rarr;</span></a>


                            </div>
                        </div>
                    </div>

                </div>
              <?php endif?>


            </div>



        </div>

        <div class="draw-buttons gal three" aria-hidden="true">
            <div class="holder">
                <span class="swiper-no"><span class="cur">1</span><span class="tot">1</span></span>
	      <span class="btn-prev">

	<svg version="1.1" class="svg left" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="60px" height="60px" viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve"><g><path d="M24.294,33.641c-0.908-0.991-1.694-1.745-2.357-2.261c-0.663-0.517-1.289-0.901-1.877-1.154v-0.461c0.677-0.329,1.333-0.748,1.969-1.256c0.635-0.51,1.395-1.257,2.276-2.242h0.79c-0.643,1.375-1.316,2.431-2.021,3.169l16.355,0v1.036l-16.355,0c0.52,0.657,0.882,1.147,1.086,1.471c0.206,0.325,0.51,0.891,0.912,1.697H24.294z"/></g></svg>
<a href="#" class="swiper-prev"></a></span>
	      <span class="btn-next">

	<svg version="1.1" class="svg right" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="60px" height="60px" viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve"><g><path d="M35.195,26.268c0.908,0.991,1.694,1.745,2.357,2.261c0.663,0.517,1.289,0.901,1.877,1.154v0.461c-0.677,0.328-1.333,0.747-1.969,1.256c-0.636,0.51-1.395,1.257-2.276,2.241h-0.79c0.643-1.375,1.316-2.431,2.021-3.169H20.06v-1.036h16.355c-0.52-0.656-0.882-1.146-1.087-1.471s-0.51-0.891-0.912-1.697H35.195z"/></g></svg>
<a href="#" class="swiper-next"></a></span>
            </div>
        </div>

    </div>

    <div class="swiper-pagination"></div>



</div>

<div id="shopify-section-1484911254397" class="shopify-section index-section featured-products-section reload-isotope home-nomargin">
    <div class="isotope-products home-content products-list border-no" data-section-id="1484911254397" data-collections_size="large" data-collections_border="no" data-collections_thumb_bg="#ffffff">
        <?php foreach(array(66, 131, 87, 75, 9, 91) as $id):?>
        <?php $shoes = \Models\Shoes::findFirst($id)?>
        <?php if($shoes):?>
        <a href="<?=$shoes->getURL()?>" class="grid-item three light">
            <img src="<?=$shoes->MainImage->thumbnailURL(800, 800)?>" data-src-retina="<?=$shoes->MainImage->thumbnailURL(800, 800)?>" srcset="data:image/gif;base64,R0lGODlhAQABAJH/AP///wAAAMDAwAAAACH5BAEAAAIALAAAAAABAAEAAAICVAEAOw==" alt="<?=$shoes->name?>">

            <div class="caption">
                <div>
                    <div>
                        <h2><?=$shoes->name?></h2>
                        <div class="price"><strong><?=$shoes->price?> грн.</strong></div>
                    </div>
                </div>
            </div>
        </a>
      <?php endif?>
        <?php endforeach?>
    </div>

</div><!-- END content_for_index -->
