<!-- Start slider area -->
<div class="slider-area">
    <div id="slider" class="nivoSlider">
        <img style ="display:none" src="/img/slider/1.jpg"  data-thumb="/img/slider/1.jpg"  alt="" title="#htmlcaption1"/>
        <img style ="display:none" src="/img/slider/2.jpg"  data-thumb="/img/slider/2.jpg"  alt="" title="#htmlcaption2"/>
    </div>
    <div id="htmlcaption1" class="pos-slideshow-caption nivo-html-caption nivo-caption">
        <div class="timing-bar"></div>
        <div class="pos-slideshow-info pos-slideshow-info1">
            <div class="container">
                <div class="pos_description hidden-xs hidden-sm">
                    <div class="title1"><span class="txt">Лучшая Обувь</span></div>
                    <div class="title2"><span class="txt">Самые Низкие Цены</span></div>
                    <div class="pos-slideshow-readmore">
                        <a href="#" title="Shop now">Купить</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="htmlcaption2" class="pos-slideshow-caption nivo-html-caption nivo-caption">
        <div class="timing-bar"></div>
        <div class="pos-slideshow-info pos-slideshow-info2">
            <div class="container">
                <div class="pos_description hidden-xs hidden-sm">
                    <div class="title1"><span class="txt">Только натуральные материалы</span></div>
                    <div class="pos-slideshow-readmore">
                        <a href="#" title="Shop now">Купить</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End slider area -->




<!-- Start categori area -->
<div class="categori-area">
    <div class="container">
        <div class="row">
            <?php $this->partial("index/partials/side_menu"); ?>
            <!-- Start categori banner -->
            <div class="col-xs-12 col-sm-8 col-md-6">
                <div class="categori-banner">
                    <div class="banner-left">
                        <div class="banner-image">
                            <a href="#">
                                <img src="img/banner/cms11.jpg" alt="">
                            </a>
                        </div>
                        <div class="banner-image">
                            <a href="#">
                                <img src="img/banner/cms12.jpg" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="banner-right">
                        <div class="banner-image">
                            <a href="#">
                                <img src="img/banner/cms13.jpg" alt="">
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End categori banner -->

            <?php $this->partial("index/partials/sale_off"); ?>
        </div>
    </div>
</div>
<!-- End categori area -->


<!-- Start purches progress -->
<div class="purches-progress-area">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12">
                <div class="area-title">
                    <h3>Purchase progress</h3>
                </div>
            </div>
            <div class="progress-area">
                <div class="col-sm-3">
                    <div class="progrtee-box icon">
                        <h4>step 1</h4>
                        <p>select your items</p>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="progrtee-box icon1">
                        <h4>step 1</h4>
                        <p>select your items</p>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="progrtee-box icon2">
                        <h4>step 1</h4>
                        <p>select your items</p>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="progrtee-box icon3">
                        <h4>step 1</h4>
                        <p>select your items</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End purches progress -->
<!-- Start featured product -->
<?php $this->partial("index/partials/featured"); ?>
<!-- End featured product -->
<!-- Start two banner area -->
<div class="two-banner-area">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-6">
                <div class="banner-left">
                    <div class="banner-image">
                        <a href="#">
                            <img src="img/banner/cms14.jpg" alt="">
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6">
                <div class="banner-right">
                    <div class="banner-image">
                        <a href="#">
                            <img src="img/banner/cms15.jpg" alt="">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End two banner area -->
<!-- Start best sellar area -->
<?php $this->partial("index/partials/bestsellers"); ?>

<!-- End best sellar area -->
<!-- Start camera and cosmatic area -->
<div class="camera-and-cosmatic-area">
    <div class="container">
        <div class="row">
            <?php $promo = \Models\PromoBlocks::findFirst("const = '".\Models\PromoBlocks::SPRING_SUMMER."'");?>
            <?php $this->partial("index/partials/season", array('promo' => $promo)); ?>

            <?php $promo = \Models\PromoBlocks::findFirst("const = '".\Models\PromoBlocks::AUTUMN_WINTER."'");?>
            <?php $this->partial("index/partials/season", array('promo' => $promo)); ?>
        </div>
    </div>
</div>


<?php $this->partial("index/partials/best_from_categories")?>

<div class="brand-and-client">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12">
                <div class="area-title">
                    <h3>BRAND & CLIENTS</h3>
                </div>
            </div>
            <div class="col-sm-12">
                <div class="brand-logo featured-product-area">
                    <div class="clients">
                        <a href="#"><img src="img/brand-logo/1.jpg" alt=""></a>
                    </div>
                    <div class="clients">
                        <a href="#"><img src="img/brand-logo/2.jpg" alt=""></a>
                    </div>
                    <div class="clients">
                        <a href="#"><img src="img/brand-logo/3.jpg" alt=""></a>
                    </div>
                    <div class="clients">
                        <a href="#"><img src="img/brand-logo/4.jpg" alt=""></a>
                    </div>
                    <div class="clients">
                        <a href="#"><img src="img/brand-logo/5.jpg" alt=""></a>
                    </div>
                    <div class="clients">
                        <a href="#"><img src="img/brand-logo/6.jpg" alt=""></a>
                    </div>
                    <div class="clients">
                        <a href="#"><img src="img/brand-logo/1.jpg" alt=""></a>
                    </div>
                    <div class="clients">
                        <a href="#"><img src="img/brand-logo/3.jpg" alt=""></a>
                    </div>
                    <div class="clients">
                        <a href="#"><img src="img/brand-logo/4.jpg" alt=""></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End brand and client -->
<!-- Start blog area -->
<div class="blog-area">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12">
                <div class="area-title">
                    <h3>The Blog</h3>
                </div>
            </div>
            <div class="blog-box featured-product-area">
                <div class="col-xs-12 col-sm-4">
                    <a href="single-blog.html"><img src="img/blog/4-home-default.jpg" alt=""></a>
                    <span class="blog-date">2015-08-12 04:40:21</span>
                    <div class="blog-info">
                        <h3><a href="single-blog.html">Share the Love for PrestaShop 1.6</a></h3>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been...</p>
                        <a href="single-blog.html" class="readmore">Read more<i class="fa fa-arrow-right"></i></a>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-4">
                    <a href="single-blog.html"><img src="img/blog/3-home-default.jpg" alt=""></a>
                    <span class="blog-date">2015-08-12 04:40:21</span>
                    <div class="blog-info">
                        <h3><a href="single-blog.html">Answers to your Questions about PrestaShop</a></h3>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been...</p>
                        <a href="single-blog.html" class="readmore">Read more<i class="fa fa-arrow-right"></i></a>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-4">
                    <a href="single-blog.html"><img src="img/blog/2-home-default.jpg" alt=""></a>
                    <span class="blog-date">2015-08-12 04:40:21</span>
                    <div class="blog-info">
                        <h3><a href="single-blog.html">What is Bootstrap? – The History and the Hype</a></h3>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been...</p>
                        <a href="single-blog.html" class="readmore">Read more<i class="fa fa-arrow-right"></i></a>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-4">
                    <a href="single-blog.html"><img src="img/blog/1-home-default.jpg" alt=""></a>
                    <span class="blog-date">2015-08-12 04:40:21</span>
                    <div class="blog-info">
                        <h3><a href="single-blog.html">From Now we are certified web agency</a></h3>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been...</p>
                        <a href="single-blog.html" class="readmore">Read more<i class="fa fa-arrow-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End blog area -->