<!-- Start categori menu -->
<div class="col-xs-12 col-sm-4 col-md-3">
    <div class="categori-menu">
        <div class="sidebar-menu-title">
            <h2><i class="fa fa-th-list"></i>Categories</h2>
        </div>
        <div class="sidebar-menu">
            <ul>
                <li><a href="shop-grid.html">Automotive & Motorcycle</a>
                    <div class="megamenudown-sub">
                        <div class="mega-top">
                            <div class="mega-item-menu">
                                <a href="shop-grid.html" class="title"><span>electronic</span></a>
                                <a href="shop-grid.html"><span>Camera & Camcorders</span></a>
                                <a href="shop-grid.html"><span>Electronic</span></a>
                                <a href="shop-grid.html"><span>Cosmetic</span></a>
                                <a href="shop-grid.html"><span>Medical & Healthcare</span></a>
                                <a href="shop-grid.html"><span>Laptop & Computer</span></a>
                                <a href="shop-grid.html"><span>Phasellus laoreet</span></a>
                            </div>
                            <div class="mega-item-menu">
                                <a href="shop-grid.html" class="title"><span>electronic</span></a>
                                <a href="shop-grid.html"><span>Camera & Camcorders</span></a>
                                <a href="shop-grid.html"><span>Electronic</span></a>
                                <a href="shop-grid.html"><span>Cosmetic</span></a>
                                <a href="shop-grid.html"><span>Medical & Healthcare</span></a>
                                <a href="shop-grid.html"><span>Laptop & Computer</span></a>
                                <a href="shop-grid.html"><span>Phasellus laoreet</span></a>
                            </div>
                            <div class="mega-item-menu">
                                <a href="shop-grid.html" class="title"><span>laptop</span></a>
                                <a href="shop-grid.html"><span>Phasellus laoreet</span></a>
                                <a href="shop-grid.html"><span>Medical & Healthcare</span></a>
                                <a href="shop-grid.html"><span>Electronic</span></a>
                                <a href="shop-grid.html"><span>Cosmetic</span></a>
                            </div>
                        </div>
                    </div>
                </li>
                <li><a href="#">Electronics</a>
                    <div class="megamenudown-sub">
                        <div class="mega-top">
                            <div class="mega-item-menu">
                                <a href="shop-grid.html" class="title"><span>camera & camcorder</span></a>
                                <a href="shop-grid.html"><span>Medical & Healthcare</span></a>
                                <a href="shop-grid.html"><span>Laptop & Computer</span></a>
                                <a href="shop-grid.html"><span>Camera</span></a>
                            </div>
                            <div class="mega-item-menu">
                                <a href="shop-grid.html" class="title"><span>Medical</span></a>
                                <a href="shop-grid.html"><span>Camera</span></a>
                                <a href="shop-grid.html"><span>Camcorders</span></a>
                                <a href="shop-grid.html"><span>Camera & Camcorders</span></a>
                            </div>
                            <div class="mega-item-menu">
                                <a href="shop-grid.html" class="title"><span>Healthcare</span></a>
                                <a href="shop-grid.html"><span>Medical</span></a>
                                <a href="shop-grid.html"><span>Healthcare</span></a>
                                <a href="shop-grid.html"><span>Medical & Healthcare</span></a>
                            </div>
                        </div>
                    </div>
                </li>
                <li><a href="shop-grid.html">Sports & Outdoors</a>
                    <div class="megamenudown-sub">
                        <div class="mega-top">
                            <div class="mega-item-menu">
                                <a href="shop-grid.html" class="title"><span>category 1</span></a>
                                <a href="shop-grid.html"><span>day</span></a>
                                <a href="shop-grid.html"><span>evening</span></a>
                                <a href="shop-grid.html"><span>night</span></a>
                            </div>
                            <div class="mega-item-menu">
                                <a href="shop-grid.html" class="title"><span>category 2</span></a>
                                <a href="shop-grid.html"><span>kids</span></a>
                                <a href="shop-grid.html"><span>men</span></a>
                                <a href="shop-grid.html"><span>Women</span></a>
                            </div>
                            <div class="mega-item-menu">
                                <a href="shop-grid.html" class="title"><span>category 3</span></a>
                                <a href="shop-grid.html"><span>clothing</span></a>
                                <a href="shop-grid.html"><span>Accessories</span></a>
                            </div>
                        </div>
                    </div>
                </li>
                <li><a href="shop-grid.html">Smartphone & Tablets</a>
                    <div class="megamenudown-sub mini">
                        <div class="mega-top">
                            <div class="mega-item-menu">
                                <a href="shop-grid.html"><span>category 1</span></a>
                                <a href="shop-grid.html"><span>category 2</span></a>
                                <a href="shop-grid.html"><span>category 3</span></a>
                            </div>
                        </div>
                    </div>
                </li>
                <li><a href="shop-grid.html">Health & Beauty</a>
                    <div class="megamenudown-sub mini">
                        <div class="mega-top">
                            <div class="mega-item-menu">
                                <a href="shop-grid.html"><span>category 1</span></a>
                                <a href="shop-grid.html"><span>category 2</span></a>
                            </div>
                        </div>
                    </div>
                </li>
                <li><a href="shop-grid.html" class="single-menu">Bags, Shoes & Accessories</a></li>
                <li><a href="shop-grid.html" class="single-menu">Computers & Networking</a></li>
                <li><a href="shop-grid.html" class="single-menu">Laptops & Accessories</a></li>
                <li><a href="shop-grid.html" class="single-menu">Entertainment</a></li>
            </ul>
        </div>
    </div>
</div>
<!-- End categori menu -->
