<div class="blog-area">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="area-title">
                    <h3>The Blog</h3>
                </div>
            </div>
            <div class="blog-box featured-product-area owl-carousel owl-theme" style="opacity: 1; display: block;">
                <div class="owl-wrapper-outer"><div class="owl-wrapper" style="width: 3200px; left: 0px; display: block;"><div class="owl-item" style="width: 400px;"><div class="col-sm-4">
                                <a href="single-blog.html"><img alt="" src="/img/blog/4-home-default.jpg"></a>
                                <span class="blog-date">2015-08-12 04:40:21</span>
                                <div class="blog-info">
                                    <h3><a href="single-blog.html">Share the Love for PrestaShop 1.6</a></h3>
                                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been...</p>
                                    <a class="readmore" href="single-blog.html">Read more<i class="fa fa-arrow-right"></i></a>
                                </div>
                            </div></div><div class="owl-item" style="width: 400px;"><div class="col-sm-4">
                                <a href="single-blog.html"><img alt="" src="/img/blog/3-home-default.jpg"></a>
                                <span class="blog-date">2015-08-12 04:40:21</span>
                                <div class="blog-info">
                                    <h3><a href="single-blog.html">Answers to your Questions about PrestaShop</a></h3>
                                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been...</p>
                                    <a class="readmore" href="single-blog.html">Read more<i class="fa fa-arrow-right"></i></a>
                                </div>
                            </div></div><div class="owl-item" style="width: 400px;"><div class="col-sm-4">
                                <a href="single-blog.html"><img alt="" src="/img/blog/2-home-default.jpg"></a>
                                <span class="blog-date">2015-08-12 04:40:21</span>
                                <div class="blog-info">
                                    <h3><a href="single-blog.html">What is Bootstrap? &ndash; The History and the Hype</a></h3>
                                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been...</p>
                                    <a class="readmore" href="single-blog.html">Read more<i class="fa fa-arrow-right"></i></a>
                                </div>
                            </div></div><div class="owl-item" style="width: 400px;"><div class="col-sm-4">
                                <a href="single-blog.html"><img alt="" src="/img/blog/1-home-default.jpg"></a>
                                <span class="blog-date">2015-08-12 04:40:21</span>
                                <div class="blog-info">
                                    <h3><a href="single-blog.html">From Now we are certified web agency</a></h3>
                                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been...</p>
                                    <a class="readmore" href="single-blog.html">Read more<i class="fa fa-arrow-right"></i></a>
                                </div>
                            </div></div></div></div>



                <div class="owl-controls clickable"><div class="owl-buttons"><div class="owl-prev"><i class="icon-left-open"><i class="fa fa-angle-left"></i></i></div><div class="owl-next"><i class="icon-right-open"><i class="fa fa-angle-right"></i></i></div></div></div></div>
        </div>
    </div>
</div>