<div class="brand-and-client">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="area-title">
                    <h3>BRAND &amp; CLIENTS</h3>
                </div>
            </div>
            <div class="col-sm-12">
                <div class="brand-logo featured-product-area owl-carousel owl-theme" style="opacity: 1; display: block;">
                    <div class="owl-wrapper-outer"><div class="owl-wrapper" style="width: 3510px; left: 0px; display: block;"><div class="owl-item" style="width: 195px;"><div class="clients">
                                    <a href="#"><img alt="" src="/img/brand-logo/1.jpg"></a>
                                </div></div><div class="owl-item" style="width: 195px;"><div class="clients">
                                    <a href="#"><img alt="" src="/img/brand-logo/2.jpg"></a>
                                </div></div><div class="owl-item" style="width: 195px;"><div class="clients">
                                    <a href="#"><img alt="" src="/img/brand-logo/3.jpg"></a>
                                </div></div><div class="owl-item" style="width: 195px;"><div class="clients">
                                    <a href="#"><img alt="" src="/img/brand-logo/4.jpg"></a>
                                </div></div><div class="owl-item" style="width: 195px;"><div class="clients">
                                    <a href="#"><img alt="" src="/img/brand-logo/5.jpg"></a>
                                </div></div><div class="owl-item" style="width: 195px;"><div class="clients">
                                    <a href="#"><img alt="" src="/img/brand-logo/6.jpg"></a>
                                </div></div><div class="owl-item" style="width: 195px;"><div class="clients">
                                    <a href="#"><img alt="" src="/img/brand-logo/1.jpg"></a>
                                </div></div><div class="owl-item" style="width: 195px;"><div class="clients">
                                    <a href="#"><img alt="" src="/img/brand-logo/3.jpg"></a>
                                </div></div><div class="owl-item" style="width: 195px;"><div class="clients">
                                    <a href="#"><img alt="" src="/img/brand-logo/4.jpg"></a>
                                </div></div></div></div>








                    <div class="owl-controls clickable"><div class="owl-buttons"><div class="owl-prev"><i class="icon-left-open"><i class="fa fa-angle-left"></i></i></div><div class="owl-next"><i class="icon-right-open"><i class="fa fa-angle-right"></i></i></div></div></div></div>
            </div>
        </div>
    </div>
</div>
