<aside id="footer" class="loading">
    <div class="social-icons">
        <a href="#">#<i class="fa fa-twitter fa-fw"></i></a>
        <a href="#">#<i class="fa fa-facebook fa-fw"></i></a>
        <a href="#">#<i class="fa fa-vimeo-square fa-fw"></i></a>
        <a href="#">#<i class="fa fa-linkedin fa-fw"></i></a>
    </div>
    <p>
        <a href="tel:+380508724698"><i class="fa fa-phone"></i>Viber: (050) 872-46-98</a><br />
        <a href="tel:+380980982137"><i class="fa fa-phone"></i>(098) 098-21-37</a>
    </p>
</aside>

