<aside id="footer" class="loading">
    <div class="social-icons">
        <a href="http://facebook.com/rumi.shoes">#<i class="fa fa-facebook fa-fw"></i></a>
        <a href="http://instagram.com/rumi.store">#<i class="fa fa-instagram fa-fw"></i></a>
    </div>

</aside>

<div class="fb-page" data-href="https://www.facebook.com/mnogoobuvicom-1128253487277273/" data-tabs="timeline" data-width="270" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/mnogoobuvicom-1128253487277273/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/mnogoobuvicom-1128253487277273/">mnogoobuvi.com</a></blockquote></div>
