<nav role="navigation" id="menu">
    <div>
        <ul class="top-menu collections-menu size-1">
            <li aria-haspopup="true" class="submenu">
                <ul style="display: block; overflow: visible;" class="sub-menu">

                    <li><a href="/shoes/index">Все коллекции</a></li>
                    <li><a href="/shoes/index?filter[23]=1">Босоножки</a></li>
                    <li><a href="/shoes/index?filter[24]=1">Туфли</a></li>
                    <li><a href="/shoes/index?filter[40]=1">Кроссовки</a></li>
                    <li><a href="/shoes/index?filter[27]=1">Сапоги</a></li>
                    <li><a href="/shoes/index?filter[29]=1">Ботильоны</a></li>
                    <li><a href="/shoes/index?filter[39]=1">Ботфорты</a></li>
                 </ul>
            </li>
        </ul>   
        <!--ul class="top-menu size-4">
            <li>
                <a href="/pages/about-us">About Us</a>
            </li>
        </ul-->
    </div>

    <a class="responsive-close" href="#" style="display: none;">
        <svg version="1.1" class="svg close" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="60px" height="60px" viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve"><polygon points="38.936,23.561 36.814,21.439 30.562,27.691 24.311,21.439 22.189,23.561 28.441,29.812   22.189,36.064 24.311,38.186 30.562,31.934 36.814,38.186 38.936,36.064 32.684,29.812 "></polygon></svg>
    </a>
</nav>
