<div id="meta">

    <div class="item responsive-menu">
        <a href="#">Menu</a>
        <svg class="svg hamburger" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="60px" height="60px" viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve"><g><rect x="18" y="20" width="25" height="4"></rect><rect x="18" y="28" width="25" height="4"></rect><rect x="18" y="36" width="25" height="4"></rect></g></svg>
    </div>


    <div class="item">
            <a href="tel:+380508724698"><i class="fa fa-phone"></i>Viber: (050) 872-46-98</a><br />
            <a href="tel:+380980982137"><i class="fa fa-phone"></i>(098) 098-21-37</a>

    </div>


</div>


