<!-- Start mainmenu-area -->
<div class="mainmenu-area">
    <div class="container">
        <div class="row">
            <div class="mainmenu">
                <nav>
                    <ul>
                        <?php $this->partial("partials/main_menu_items"); ?>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- End mainmenu-area -->
<!-- Start mobile menu -->
<div class="mobile-menu-area">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 np">
                <div class="mobile-menu">
                    <nav id="dropdown">
                        <ul class="nav">
                            <?php $this->partial("partials/main_menu_items"); ?>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End mobile menu -->