<li><a class="home" href="/">Новинки</a>
    <ul>
        <li><a href="index-2.html"><span>Home2</span></a></li>
        <li><a href="index-3.html"><span>Home3</span></a></li>
        <li><a href="index-4.html"><span>Home4</span></a></li>
    </ul>
</li>
<li><a href="about-us.html">Магазин</a></li>
<li><a href="shop-grid.html">Как купить</a></li>
<li><a href="#">Контакты</a></li>
<li><a href="blog.html">Blog</a>
    <ul>
        <li><a href="blog.html">Blog</a></li>
        <li><a href="blog-non-sidebar.html">Blog non sidebar</a></li>
        <li><a href="single-blog.html">Single blog</a></li>
    </ul>
</li>
<li><a href="">Pages</a>
    <ul>
        <li><a href="about-us.html"><span>About us</span></a></li>
        <li><a href="blog.html"><span>Blog</span></a></li>
        <li><a href="blog-non-sidebar.html"><span>blog non sidebar</span></a></li>
        <li><a href="single-blog.html"><span>single blog</span></a></li>
        <li><a href="shop-grid.html"><span>shop grid</span></a></li>
        <li><a href="shop-list.html"><span>shop list</span></a></li>
        <li><a href="single-product.html"><span>single product</span></a></li>
        <li><a href="cart.html"><span>cart</span></a></li>
        <li><a href="wishlists.html"><span>wishlists</span></a></li>
        <li><a href="checkout.html"><span>checkout</span></a></li>
        <li><a href="contact-us.html"><span>contact us</span></a></li>
        <li><a href="404.html"><span>404</span></a></li>
    </ul>
</li>
<li><a href="contact-us.html">Contact</a></li>
