<li><a class="home" href="/">Новинки</a>
    <ul>
        <li><a href="index-2.html"><span>Home2</span></a></li>
        <li><a href="index-3.html"><span>Home3</span></a></li>
        <li><a href="index-4.html"><span>Home4</span></a></li>
    </ul>
</li>
<li><a href="about-us.html">Распродажа %</a></li>
<li><a href="about-us.html">Магазин</a></li>
<li><a href="shop-grid.html">Как купить</a></li>
<li><a href="#">Контакты</a></li>

