<div id="shopify-section-slideshow" class="shopify-section">

    <div id="home-slider" class="swiper-container" data-section-id="slideshow" data-transition="slide" data-autoplay="true" data-timer="7">

        <div class="swiper-wrapper">



            <div class="slide swiper-slide slide--1484211369679"  data-index="1">
                <?php $slide = \Models\Shoes::findFirst(140)?>


                <div class="slide-img image" style="background-image:url(<?=$slide->MainImage->originalURL()?>)">



                    <img src="<?=$slide->MainImage->originalURL()?> " alt="" />

                    <div class="slide-caption right light">
                        <div class="table-display">
                            <div>


                                <span class="label a">Final Clearance Sale</span>



                                <h2 class="label b">NATURAL COSMETICS FOR MEN</h2>



                                <span class="label c">STARTING FROM $39.00</span>



                                <a class="button dark label d" href="http://king-theme.myshopify.com/collections/furniture">Learn more<span>&rarr;</span></a>


                            </div>
                        </div>
                    </div>

                </div>



            </div>



            <div class="slide swiper-slide slide--1484211385979"  data-index="2">
                <?php $slide = \Models\Shoes::findFirst(141)?>


                <div class="slide-img image" style="background-image:url(<?=$slide->MainImage->originalURL()?>)">



                    <img src="<?=$slide->MainImage->originalURL()?>" alt="" />

                    <div class="slide-caption right light">
                        <div class="table-display">
                            <div>


                                <span class="label a">New Arrival</span>



                                <h2 class="label b">PERSONAL ENVIRONMENT</h2>



                                <span class="label c">STARTING FROM $68.00</span>



                                <a class="button dark label d" href="http://king-theme.myshopify.com/collections/gadgets/products/personal-environment-monitor">Learn more<span>&rarr;</span></a>


                            </div>
                        </div>
                    </div>

                </div>



            </div>



        </div>

        <div class="draw-buttons gal three" aria-hidden="true">
            <div class="holder">
                <span class="swiper-no"><span class="cur">1</span><span class="tot">1</span></span>
	      <span class="btn-prev">

	<svg version="1.1" class="svg left" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="60px" height="60px" viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve"><g><path d="M24.294,33.641c-0.908-0.991-1.694-1.745-2.357-2.261c-0.663-0.517-1.289-0.901-1.877-1.154v-0.461c0.677-0.329,1.333-0.748,1.969-1.256c0.635-0.51,1.395-1.257,2.276-2.242h0.79c-0.643,1.375-1.316,2.431-2.021,3.169l16.355,0v1.036l-16.355,0c0.52,0.657,0.882,1.147,1.086,1.471c0.206,0.325,0.51,0.891,0.912,1.697H24.294z"/></g></svg>
<a href="#" class="swiper-prev"></a></span>
	      <span class="btn-next">

	<svg version="1.1" class="svg right" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="60px" height="60px" viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve"><g><path d="M35.195,26.268c0.908,0.991,1.694,1.745,2.357,2.261c0.663,0.517,1.289,0.901,1.877,1.154v0.461c-0.677,0.328-1.333,0.747-1.969,1.256c-0.636,0.51-1.395,1.257-2.276,2.241h-0.79c0.643-1.375,1.316-2.431,2.021-3.169H20.06v-1.036h16.355c-0.52-0.656-0.882-1.146-1.087-1.471s-0.51-0.891-0.912-1.697H35.195z"/></g></svg>
<a href="#" class="swiper-next"></a></span>
            </div>
        </div>

    </div>

    <div class="swiper-pagination"></div>



</div>

<div id="shopify-section-1484911254397" class="shopify-section index-section featured-products-section reload-isotope home-nomargin">
    <div class="isotope-products home-content products-list border-no" data-section-id="1484911254397" data-collections_size="large" data-collections_border="no" data-collections_thumb_bg="#ffffff">

        <?php $shoes = \Models\Shoes::findFirst(66)?>
        <a href="/products/louis-erard" class="grid-item three light">
            <img src="<?=$shoes->MainImage->originalURL()?>" data-src-retina="<?=$shoes->MainImage->originalURL()?>" srcset="data:image/gif;base64,R0lGODlhAQABAJH/AP///wAAAMDAwAAAACH5BAEAAAIALAAAAAABAAEAAAICVAEAOw==" alt="<?=$shoes->name?>">

            <div class="caption">
                <div>

                    <div>

                        <h2><?=$shoes->name?></h2>

                        <div class="price">



                            <strong><?=$shoes->price?> грн.</strong>



                        </div>

                    </div>

                </div>


            </div>



        </a>


        <?php $shoes = \Models\Shoes::findFirst(131)?>
        <a href="/products/unicon-test-short-sleeve" class="grid-item three light">
            <img src="<?=$shoes->MainImage->originalURL()?>" data-src-retina="<?=$shoes->MainImage->originalURL()?>" srcset="data:image/gif;base64,R0lGODlhAQABAJH/AP///wAAAMDAwAAAACH5BAEAAAIALAAAAAABAAEAAAICVAEAOw==" alt="<?=$shoes->name?>">



            <div class="caption">


                <div>

                    <div>

                        <h2><?=$shoes->name?></h2>

                        <div class="price">





                            <strong><?=$shoes->price?> грн.</strong>



                        </div>

                    </div>

                </div>


            </div>



        </a>











        <a href="/products/maple-ipad-sleeve" class="grid-item three light">






            <img src="//cdn.shopify.com/s/files/1/0691/8855/products/3_new_640x.jpg?v=1427796941" data-src-retina="//cdn.shopify.com/s/files/1/0691/8855/products/3_new_1024x.jpg?v=1427796941" srcset="data:image/gif;base64,R0lGODlhAQABAJH/AP///wAAAMDAwAAAACH5BAEAAAIALAAAAAABAAEAAAICVAEAOw==" alt="Cuber Lamp">



            <div class="caption">


                <div>

                    <div>

                        <h2>Cuber Lamp</h2>

                        <div class="price">



                            <strong>$89.00</strong>


                            <span class="info">$109.00</span>


                        </div>

                    </div>

                </div>


            </div>



            <span class="add sale"><span>On Sale</span></span>



        </a>











        <a href="/products/withings-activite" class="grid-item three light">






            <img src="//cdn.shopify.com/s/files/1/0691/8855/products/4_640x.jpg?v=1420809371" data-src-retina="//cdn.shopify.com/s/files/1/0691/8855/products/4_1024x.jpg?v=1420809371" srcset="data:image/gif;base64,R0lGODlhAQABAJH/AP///wAAAMDAwAAAACH5BAEAAAIALAAAAAABAAEAAAICVAEAOw==" alt="Activité Watch">



            <div class="caption">


                <div>

                    <div>

                        <h2>Activité Watch</h2>

                        <div class="price">



                            <strong>$450.00</strong>


                            <span class="info">$500.00</span>


                        </div>

                    </div>

                </div>


            </div>



            <span class="add sale"><span>On Sale</span></span>



        </a>











        <a href="/products/key-fold" class="grid-item three light">






            <img src="//cdn.shopify.com/s/files/1/0691/8855/products/5_640x.jpg?v=1427782899" data-src-retina="//cdn.shopify.com/s/files/1/0691/8855/products/5_1024x.jpg?v=1427782899" srcset="data:image/gif;base64,R0lGODlhAQABAJH/AP///wAAAMDAwAAAACH5BAEAAAIALAAAAAABAAEAAAICVAEAOw==" alt="Curvy Shelf">



            <div class="caption">


                <div>

                    <div>

                        <h2>Curvy Shelf</h2>

                        <div class="price">



                            <strong>$23.00</strong>



                        </div>

                    </div>

                </div>


            </div>



        </a>











        <a href="/products/molded-plywood-lounge-chair" class="grid-item three light">






            <img src="//cdn.shopify.com/s/files/1/0691/8855/products/15_640x.jpg?v=1427792647" data-src-retina="//cdn.shopify.com/s/files/1/0691/8855/products/15_1024x.jpg?v=1427792647" srcset="data:image/gif;base64,R0lGODlhAQABAJH/AP///wAAAMDAwAAAACH5BAEAAAIALAAAAAABAAEAAAICVAEAOw==" alt="Scotch Holder">



            <div class="caption">


                <div>

                    <div>

                        <h2>Scotch Holder</h2>

                        <div class="price">



                            <strong>$24.00</strong>



                        </div>

                    </div>

                </div>


            </div>



        </a>






    </div>

</div><!-- END content_for_index -->
