<div id="shopify-section-collection-page" class="shopify-section reload-isotope collection-page mount-overlay">

    <div class="isotope-products border-no" data-section-id="collection-page" data-collections_size="small" data-collections_border="no" data-collections_thumb_bg="#ffffff">
        <?php foreach($shoes->items as $item):?>
        <?php
        if($filter) {
            foreach ($filter as $attribute_id => $v) {
                if (!$item->hasAttributeId($attribute_id)) {
                    continue 2;
                }
            }
        }
        ?>

        <a href="<?=$item->getURL()?>" class="grid-item three light">
            <?php if($item->MainImage):?>
              <img src="<?=$item->MainImage->thumbnailURL(800, 800)?>"  srcset="data:image/gif;base64,R0lGODlhAQABAJH/AP///wAAAMDAwAAAACH5BAEAAAIALAAAAAABAAEAAAICVAEAOw==" alt="Wild Clock">
            <?php endif?>
            <div class="caption">
                <div>
                    <div>
                        <h2><?=$item->name?></h2>
                        <div class="price"><strong><?=$item->price?> грн.</strong></div>
                    </div>
                </div>
            </div>
        </a>
        <?php endforeach?>
    </div>
</div>
