<div class="page-content">
    <!-- Start breadcume area -->
    <div class="breadcume-area">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="breadcrumb">
                        <a class="home" href="/" title="Return to Home"><i class="fa fa-home"></i></a>
                        <span class="navigation-pipe">&gt;</span>
                        Electronics
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End breadcume area -->
    <!-- Start shop area -->
    <div class="shop-area">
        <div class="container">
            <div class="row">
                <!-- Start shop categori area -->
                <div class="col-xs-12 col-sm-4 col-md-3">
                    <div class="shop-categori-area">
                        <div class="sidebar-menu-title">
                            <h2><i class="fa fa-th-list"></i>Catalog</h2>
                        </div>
                        <div class="shop-categori">
                            <div class="shop-categori-inner">
                                <!-- Start Categori -->
                                <div class="categoris categori-border">
                                    <span class="cat-title">Categories</span>
                                    <ul>
                                        <li>
                                            <span><input type="checkbox" class="checkbox"></span>
                                            <label>
                                                <a href="">category 1<span> (17)</span></a>
                                            </label>
                                        </li>
                                        <li>
                                            <span><input type="checkbox" class="checkbox"></span>
                                            <label>
                                                <a href="">category 2<span> (17)</span></a>
                                            </label>
                                        </li>
                                        <li>
                                            <span><input type="checkbox" class="checkbox"></span>
                                            <label>
                                                <a href="">category 3<span> (17)</span></a>
                                            </label>
                                        </li>
                                    </ul>
                                </div>
                                <!-- End Categori -->
                                <!-- Start Categori -->
                                <div class="categoris categori-border">
                                    <span class="cat-title">Availability</span>
                                    <ul>
                                        <li>
                                            <span><input type="checkbox" class="checkbox"></span>
                                            <label>
                                                <a href="">In stock<span> (17)</span></a>
                                            </label>
                                        </li>
                                    </ul>
                                </div>
                                <!-- End Categori -->
                                <!-- Start Categori -->
                                <div class="categoris categori-border">
                                    <span class="cat-title">Condition</span>
                                    <ul>
                                        <li>
                                            <span><input type="checkbox" class="checkbox"></span>
                                            <label>
                                                <a href="">New<span> (17)</span></a>
                                            </label>
                                        </li>
                                    </ul>
                                </div>
                                <!-- End Categori -->
                                <!-- Start Categori -->
                                <div class="categoris categori-border">
                                    <span class="cat-title">Manufacturer</span>
                                    <ul>
                                        <li>
                                            <span><input type="checkbox" class="checkbox"></span>
                                            <label>
                                                <a href="">Fashion Manufacturer<span> (17)</span></a>
                                            </label>
                                        </li>
                                    </ul>
                                </div>
                                <!-- End Categori -->
                                <!-- Start Categori -->
                                <div class="categoris categori-border">
                                    <span class="cat-title">Price</span>
                                    <ul>
                                        <li class="price-range">
                                            <label for="amount">Range: <input type="text" style="border:0; color:#f6931f; font-weight:bold;" readonly="" id="amount"></label>
                                            <div id="slider-range" class="ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all"><div class="ui-slider-range ui-widget-header ui-corner-all" style="left: 0%; width: 80%;"></div><span tabindex="0" class="ui-slider-handle ui-state-default ui-corner-all" style="left: 0%;"></span><span tabindex="0" class="ui-slider-handle ui-state-default ui-corner-all" style="left: 80%;"></span></div>
                                        </li>
                                    </ul>
                                </div>
                                <!-- End Categori -->
                                <!-- Start Categori -->
                                <div class="categoris categori-border">
                                    <span class="cat-title">Size</span>
                                    <ul>
                                        <li>
                                            <span><input type="checkbox" class="checkbox"></span>
                                            <label>
                                                <a href="">S<span> (17)</span></a>
                                            </label>
                                        </li>
                                        <li>
                                            <span><input type="checkbox" class="checkbox"></span>
                                            <label>
                                                <a href="">M<span> (17)</span></a>
                                            </label>
                                        </li>
                                        <li>
                                            <span><input type="checkbox" class="checkbox"></span>
                                            <label>
                                                <a href="">L<span> (17)</span></a>
                                            </label>
                                        </li>
                                    </ul>
                                </div>
                                <!-- End Categori -->
                                <!-- Start Categori -->
                                <div class="categoris categori-border">
                                    <span class="cat-title">Compositions</span>
                                    <ul>
                                        <li>
                                            <span><input type="checkbox" class="checkbox"></span>
                                            <label>
                                                <a href="">Cotton<span> (3)</span></a>
                                            </label>
                                        </li>
                                        <li>
                                            <span><input type="checkbox" class="checkbox"></span>
                                            <label>
                                                <a href="">Polyester<span> (12)</span></a>
                                            </label>
                                        </li>
                                        <li>
                                            <span><input type="checkbox" class="checkbox"></span>
                                            <label>
                                                <a href="">Viscose<span> (2)</span></a>
                                            </label>
                                        </li>
                                    </ul>
                                </div>
                                <!-- End Categori -->
                                <!-- Start Categori -->
                                <div class="categoris categori-border">
                                    <span class="cat-title">Styles</span>
                                    <ul>
                                        <li>
                                            <span><input type="checkbox" class="checkbox"></span>
                                            <label>
                                                <a href="">Casual<span> (3)</span></a>
                                            </label>
                                        </li>
                                        <li>
                                            <span><input type="checkbox" class="checkbox"></span>
                                            <label>
                                                <a href="">Dressy<span> (1)</span></a>
                                            </label>
                                        </li>
                                        <li>
                                            <span><input type="checkbox" class="checkbox"></span>
                                            <label>
                                                <a href="">Girly<span> (13)</span></a>
                                            </label>
                                        </li>
                                    </ul>
                                </div>
                                <!-- End Categori -->
                                <!-- Start Categori -->
                                <div class="categoris categori-border">
                                    <span class="cat-title">Properties</span>
                                    <ul>
                                        <li>
                                            <span><input type="checkbox" class="checkbox"></span>
                                            <label>
                                                <a href="">Colorful Dress<span> (1)</span></a>
                                            </label>
                                        </li>
                                        <li>
                                            <span><input type="checkbox" class="checkbox"></span>
                                            <label>
                                                <a href="">Maxi Dress<span> (1)</span></a>
                                            </label>
                                        </li>
                                        <li>
                                            <span><input type="checkbox" class="checkbox"></span>
                                            <label>
                                                <a href="">Midi Dress<span> (11)</span></a>
                                            </label>
                                        </li>
                                        <li>
                                            <span><input type="checkbox" class="checkbox"></span>
                                            <label>
                                                <a href="">Short Dress<span> (2)</span></a>
                                            </label>
                                        </li>
                                        <li>
                                            <span><input type="checkbox" class="checkbox"></span>
                                            <label>
                                                <a href="">Short Sleeve<span> (2)</span></a>
                                            </label>
                                        </li>
                                    </ul>
                                </div>
                                <!-- End Categori -->
                            </div>
                        </div>
                        <div class="tag-area">
                            <h2 class="tag-title">Tags</h2>
                            <div class="tags">
                                <a href="#">camera</a>
                                <a href="#">mobile</a>
                                <a href="#">electronic</a>
                                <a href="#">destop</a>
                                <a href="#">tablet</a>
                                <a href="#">accessories</a>
                                <a href="#">camcorder</a>
                                <a href="#">laptop</a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End shop categori area -->
                <!-- Start categori content -->
                <div class="col-xs-12 col-sm-8 col-md-9">
                    <div class="categori-content" id="content-shop">
                        <div class="categori-baner">
                            <img alt="" src="img/shop/sports-outdoors.jpg">
                        </div>
                        <h1 class="page-heading product-listing"><span class="cat-name">Electronics</span><span class="heading-counter">There are 17 products.</span>
                        </h1>
                        <!-- Start catagori short -->
                        <div class="catagori-short">
                            <ul data-tabs="tabs" class="nav nav-tabs" id="gridlist">
                                <li class="active"><a data-toggle="tab" href="#grid"><i class="fa fa-th-large"></i></a></li>
                                <li><a data-toggle="tab" href="#list"><i class="fa fa-th-list"></i></a></li>
                            </ul>
                            <div class="chose-box">
                                <p class="selector1 hidden-xs">
                                    <label>Sort by</label>
                                    <select id="selectProductSort1" class="selectProductSort form-control">
                                        <option value="position:asc" selected="selected">--</option>
                                        <option value="price:asc">Price: Lowest first</option>
                                        <option value="price:desc">Price: Highest first</option>
                                        <option value="name:asc">Product Name: A to Z</option>
                                        <option value="name:desc">Product Name: Z to A</option>
                                        <option value="quantity:desc">In stock</option>
                                        <option value="reference:asc">Reference: Lowest first</option>
                                        <option value="reference:desc">Reference: Highest first</option>
                                    </select>
                                </p>
                                <p class="selector1 selector2">
                                    <label>Show</label>
                                    <select id="selectProductSort2" class="selectProductSort form-control">
                                        <option value="position:asc" selected="selected">12</option>
                                        <option value="price:asc">24</option>
                                    </select>
                                </p>
                            </div>
                        </div>
                        <!-- End catagori short -->
                        <div class="tab-content" id="my-tab-content">
                            <!-- Start categori grid view -->
                            <div class="tab-pane active categoti-grid-view row" id="grid">
                                <!-- Start featured item -->
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <div class="featured-inner">
                                        <div class="featured-image">
                                            <a href="single-product.html">
                                                <img alt="" src="img/product/faded-short-sleeves-tshirt.jpg">
                                            </a>
                                        </div>
                                        <div class="featured-info">
                                            <a href="single-product.html">Faded Short Sleeves T-shirt</a>
                                            <p class="reating">
                                                            <span class="rate">
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                            </span>
                                            </p>
                                            <span class="price">$16.51</span>
                                            <div class="featured-button">
                                                <a class="wishlist" href="wishlists.html"><i class="fa fa-heart"></i></a>
                                                <a class="fetu-comment" href="#"><i class="fa fa-signal"></i></a>
                                                <a class="add-to-card" href="cart.html"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End featured item -->
                                <!-- Start featured item -->
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <div class="featured-inner">
                                        <div class="featured-image">
                                            <a href="single-product.html">
                                                <img alt="" src="img/product/blouse.jpg">
                                            </a>
                                        </div>
                                        <div class="featured-info">
                                            <a href="single-product.html">Blouse</a>
                                            <p class="reating">
                                                            <span class="rate">
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                            </span>
                                            </p>
                                            <span class="price">$27.00</span>
                                            <div class="featured-button">
                                                <a class="wishlist" href="wishlists.html"><i class="fa fa-heart"></i></a>
                                                <a class="fetu-comment" href="#"><i class="fa fa-signal"></i></a>
                                                <a class="add-to-card" href="cart.html"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End featured item -->
                                <!-- Start featured item -->
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <div class="featured-inner">
                                        <div class="featured-image">
                                            <a href="single-product.html">
                                                <img alt="" src="img/product/printed-dress1.jpg">
                                            </a>
                                            <span class="price-percent-reduction">-20%</span>
                                        </div>
                                        <div class="featured-info">
                                            <a href="single-product.html">Printed Dress</a>
                                            <p class="reating">
                                                            <span class="rate">
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                            </span>
                                            </p>
                                            <span class="price">$26.00</span>
                                            <div class="featured-button">
                                                <a class="wishlist" href="wishlists.html"><i class="fa fa-heart"></i></a>
                                                <a class="fetu-comment" href="#"><i class="fa fa-signal"></i></a>
                                                <a class="add-to-card" href="cart.html"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End featured item -->
                                <!-- Start featured item -->
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <div class="featured-inner">
                                        <div class="featured-image">
                                            <a href="single-product.html">
                                                <img alt="" src="img/product/printed-dress2.jpg">
                                            </a>
                                        </div>
                                        <div class="featured-info">
                                            <a href="single-product.html">Printed Dress</a>
                                            <p class="reating">
                                                            <span class="rate">
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                            </span>
                                            </p>
                                            <span class="price">$50.00</span>
                                            <div class="featured-button">
                                                <a class="wishlist" href="wishlists.html"><i class="fa fa-heart"></i></a>
                                                <a class="fetu-comment" href="#"><i class="fa fa-signal"></i></a>
                                                <a class="add-to-card" href="cart.html"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End featured item -->
                                <!-- Start featured item -->
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <div class="featured-inner">
                                        <div class="featured-image">
                                            <a href="single-product.html">
                                                <img alt="" src="img/product/printed-summer-dress4.jpg">
                                            </a>
                                            <span class="price-percent-reduction">-20%</span>
                                        </div>
                                        <div class="featured-info">
                                            <a href="single-product.html">Printed Summer Dress</a>
                                            <p class="reating">
                                                            <span class="rate">
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                            </span>
                                            </p>
                                            <span class="price">$28.00</span>
                                            <div class="featured-button">
                                                <a class="wishlist" href="wishlists.html"><i class="fa fa-heart"></i></a>
                                                <a class="fetu-comment" href="#"><i class="fa fa-signal"></i></a>
                                                <a class="add-to-card" href="cart.html"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End featured item -->
                                <!-- Start featured item -->
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <div class="featured-inner">
                                        <div class="featured-image">
                                            <a href="single-product.html">
                                                <img alt="" src="img/product/printed-summer-dress.jpg">
                                            </a>
                                        </div>
                                        <div class="featured-info">
                                            <a href="single-product.html">Printed Summer Dress</a>
                                            <p class="reating">
                                                            <span class="rate">
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                            </span>
                                            </p>
                                            <span class="price">$30.00</span>
                                            <div class="featured-button">
                                                <a class="wishlist" href="wishlists.html"><i class="fa fa-heart"></i></a>
                                                <a class="fetu-comment" href="#"><i class="fa fa-signal"></i></a>
                                                <a class="add-to-card" href="cart.html"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End featured item -->
                                <!-- Start featured item -->
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <div class="featured-inner">
                                        <div class="featured-image">
                                            <a href="single-product.html">
                                                <img alt="" src="img/product/printed-chiffon-dress1.jpg">
                                            </a>
                                        </div>
                                        <div class="featured-info">
                                            <a href="single-product.html">Printed Chiffon Dress</a>
                                            <p class="reating">
                                                            <span class="rate">
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                            </span>
                                            </p>
                                            <span class="price">$16.40</span>
                                            <div class="featured-button">
                                                <a class="wishlist" href="wishlists.html"><i class="fa fa-heart"></i></a>
                                                <a class="fetu-comment" href="#"><i class="fa fa-signal"></i></a>
                                                <a class="add-to-card" href="cart.html"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End featured item -->
                                <!-- Start featured item -->
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <div class="featured-inner">
                                        <div class="featured-image">
                                            <a href="single-product.html">
                                                <img alt="" src="img/product/printed-chiffon-dress4.jpg">
                                            </a>
                                            <span class="price-percent-reduction">-20%</span>
                                        </div>
                                        <div class="featured-info">
                                            <a href="single-product.html">Printed Chiffon Dress</a>
                                            <p class="reating">
                                                            <span class="rate">
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                            </span>
                                            </p>
                                            <span class="price">$16.40</span>
                                            <div class="featured-button">
                                                <a class="wishlist" href="wishlists.html"><i class="fa fa-heart"></i></a>
                                                <a class="fetu-comment" href="#"><i class="fa fa-signal"></i></a>
                                                <a class="add-to-card" href="cart.html"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End featured item -->
                                <!-- Start featured item -->
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <div class="featured-inner">
                                        <div class="featured-image">
                                            <a href="single-product.html">
                                                <img alt="" src="img/product/printed-chiffon-dress8.jpg">
                                            </a>
                                            <span class="price-percent-reduction">-20%</span>
                                        </div>
                                        <div class="featured-info">
                                            <a href="single-product.html">Printed Chiffon Dress</a>
                                            <p class="reating">
                                                            <span class="rate">
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                            </span>
                                            </p>
                                            <span class="price">$16.40</span>
                                            <div class="featured-button">
                                                <a class="wishlist" href="wishlists.html"><i class="fa fa-heart"></i></a>
                                                <a class="fetu-comment" href="#"><i class="fa fa-signal"></i></a>
                                                <a class="add-to-card" href="cart.html"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End featured item -->
                                <!-- Start featured item -->
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <div class="featured-inner">
                                        <div class="featured-image">
                                            <a href="single-product.html">
                                                <img alt="" src="img/product/printed-chiffon-dress5.jpg">
                                            </a>
                                            <span class="price-percent-reduction">-20%</span>
                                        </div>
                                        <div class="featured-info">
                                            <a href="single-product.html">Printed Chiffon Dress</a>
                                            <p class="reating">
                                                            <span class="rate">
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                            </span>
                                            </p>
                                            <span class="price">$306.40</span>
                                            <div class="featured-button">
                                                <a class="wishlist" href="wishlists.html"><i class="fa fa-heart"></i></a>
                                                <a class="fetu-comment" href="#"><i class="fa fa-signal"></i></a>
                                                <a class="add-to-card" href="cart.html"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End featured item -->
                                <!-- Start featured item -->
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <div class="featured-inner">
                                        <div class="featured-image">
                                            <a href="single-product.html">
                                                <img alt="" src="img/product/printed-chiffon-dress3.jpg">
                                            </a>
                                            <span class="price-percent-reduction">-20%</span>
                                        </div>
                                        <div class="featured-info">
                                            <a href="single-product.html">Printed Chiffon Dress</a>
                                            <p class="reating">
                                                            <span class="rate">
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                            </span>
                                            </p>
                                            <span class="price">$26.40</span>
                                            <div class="featured-button">
                                                <a class="wishlist" href="wishlists.html"><i class="fa fa-heart"></i></a>
                                                <a class="fetu-comment" href="#"><i class="fa fa-signal"></i></a>
                                                <a class="add-to-card" href="cart.html"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End featured item -->
                                <!-- Start featured item -->
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <div class="featured-inner">
                                        <div class="featured-image">
                                            <a href="single-product.html">
                                                <img alt="" src="img/product/printed-chiffon-dresst.jpg">
                                            </a>
                                            <span class="price-percent-reduction">-20%</span>
                                        </div>
                                        <div class="featured-info">
                                            <a href="single-product.html">Printed Chiffon Dress</a>
                                            <p class="reating">
                                                            <span class="rate">
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                            </span>
                                            </p>
                                            <span class="price">$26.40</span>
                                            <div class="featured-button">
                                                <a class="wishlist" href="wishlists.html"><i class="fa fa-heart"></i></a>
                                                <a class="fetu-comment" href="#"><i class="fa fa-signal"></i></a>
                                                <a class="add-to-card" href="cart.html"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End featured item -->
                            </div>
                            <!-- End categori grid view -->
                            <div class="tab-pane categori-list-view row" id="list">
                                <!-- Start featured item -->
                                <div class="col-sm-12">
                                    <div class="featured-inner">
                                        <div class="featured-image">
                                            <a href="single-product.html">
                                                <img alt="" src="img/product/faded-short-sleeves-tshirt.jpg">
                                            </a>
                                        </div>
                                        <div class="featured-info">
                                            <a href="single-product.html">Faded Short Sleeves T-shirt</a>
                                            <p class="reating">
                                                            <span class="rate">
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                            </span>
                                            </p>
                                            <p class="product-text">Faded short sleeves t-shirt with high neckline. Soft and stretchy material for a comfortable fit. Accessorize with a straw hat and you're ready for summer! </p>
                                            <span class="price">$16.51</span>
                                            <div class="featured-button">
                                                <a class="wishlist" href="wishlists.html"><i class="fa fa-heart"></i></a>
                                                <a class="fetu-comment" href="#"><i class="fa fa-signal"></i></a>
                                                <a class="add-to-card" href="cart.html"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End featured item -->
                                <!-- Start featured item -->
                                <div class="col-sm-12">
                                    <div class="featured-inner">
                                        <div class="featured-image">
                                            <a href="single-product.html">
                                                <img alt="" src="img/product/blouse.jpg">
                                            </a>
                                        </div>
                                        <div class="featured-info">
                                            <a href="single-product.html">Blouse</a>
                                            <p class="reating">
                                                            <span class="rate">
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                            </span>
                                            </p>
                                            <p class="product-text">Faded short sleeves t-shirt with high neckline. Soft and stretchy material for a comfortable fit. Accessorize with a straw hat and you're ready for summer! </p>
                                            <span class="price">$27.00</span>
                                            <div class="featured-button">
                                                <a class="wishlist" href="wishlists.html"><i class="fa fa-heart"></i></a>
                                                <a class="fetu-comment" href="#"><i class="fa fa-signal"></i></a>
                                                <a class="add-to-card" href="cart.html"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End featured item -->
                                <!-- Start featured item -->
                                <div class="col-sm-12">
                                    <div class="featured-inner">
                                        <div class="featured-image">
                                            <a href="single-product.html">
                                                <img alt="" src="img/product/printed-dress1.jpg">
                                            </a>
                                            <span class="price-percent-reduction">-20%</span>
                                        </div>
                                        <div class="featured-info">
                                            <a href="single-product.html">Printed Dress</a>
                                            <p class="reating">
                                                            <span class="rate">
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                            </span>
                                            </p>
                                            <p class="product-text">Faded short sleeves t-shirt with high neckline. Soft and stretchy material for a comfortable fit. Accessorize with a straw hat and you're ready for summer! </p>
                                            <span class="price">$26.00</span>
                                            <div class="featured-button">
                                                <a class="wishlist" href="wishlists.html"><i class="fa fa-heart"></i></a>
                                                <a class="fetu-comment" href="#"><i class="fa fa-signal"></i></a>
                                                <a class="add-to-card" href="cart.html"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End featured item -->
                                <!-- Start featured item -->
                                <div class="col-sm-12">
                                    <div class="featured-inner">
                                        <div class="featured-image">
                                            <a href="single-product.html">
                                                <img alt="" src="img/product/printed-dress2.jpg">
                                            </a>
                                        </div>
                                        <div class="featured-info">
                                            <a href="single-product.html">Printed Dress</a>
                                            <p class="reating">
                                                            <span class="rate">
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                            </span>
                                            </p>
                                            <p class="product-text">Faded short sleeves t-shirt with high neckline. Soft and stretchy material for a comfortable fit. Accessorize with a straw hat and you're ready for summer! </p>
                                            <span class="price">$50.00</span>
                                            <div class="featured-button">
                                                <a class="wishlist" href="wishlists.html"><i class="fa fa-heart"></i></a>
                                                <a class="fetu-comment" href="#"><i class="fa fa-signal"></i></a>
                                                <a class="add-to-card" href="cart.html"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End featured item -->
                                <!-- Start featured item -->
                                <div class="col-sm-12">
                                    <div class="featured-inner">
                                        <div class="featured-image">
                                            <a href="single-product.html">
                                                <img alt="" src="img/product/printed-summer-dress4.jpg">
                                            </a>
                                            <span class="price-percent-reduction">-20%</span>
                                        </div>
                                        <div class="featured-info">
                                            <a href="single-product.html">Printed Summer Dress</a>
                                            <p class="reating">
                                                            <span class="rate">
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                            </span>
                                            </p>
                                            <p class="product-text">Faded short sleeves t-shirt with high neckline. Soft and stretchy material for a comfortable fit. Accessorize with a straw hat and you're ready for summer! </p>
                                            <span class="price">$28.00</span>
                                            <div class="featured-button">
                                                <a class="wishlist" href="wishlists.html"><i class="fa fa-heart"></i></a>
                                                <a class="fetu-comment" href="#"><i class="fa fa-signal"></i></a>
                                                <a class="add-to-card" href="cart.html"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End featured item -->
                                <!-- Start featured item -->
                                <div class="col-sm-12">
                                    <div class="featured-inner">
                                        <div class="featured-image">
                                            <a href="single-product.html">
                                                <img alt="" src="img/product/printed-summer-dress.jpg">
                                            </a>
                                        </div>
                                        <div class="featured-info">
                                            <a href="single-product.html">Printed Summer Dress</a>
                                            <p class="reating">
                                                            <span class="rate">
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                            </span>
                                            </p>
                                            <p class="product-text">Faded short sleeves t-shirt with high neckline. Soft and stretchy material for a comfortable fit. Accessorize with a straw hat and you're ready for summer! </p>
                                            <span class="price">$30.00</span>
                                            <div class="featured-button">
                                                <a class="wishlist" href="wishlists.html"><i class="fa fa-heart"></i></a>
                                                <a class="fetu-comment" href="#"><i class="fa fa-signal"></i></a>
                                                <a class="add-to-card" href="cart.html"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End featured item -->
                                <!-- Start featured item -->
                                <div class="col-sm-12">
                                    <div class="featured-inner">
                                        <div class="featured-image">
                                            <a href="single-product.html">
                                                <img alt="" src="img/product/printed-chiffon-dress1.jpg">
                                            </a>
                                        </div>
                                        <div class="featured-info">
                                            <a href="single-product.html">Printed Chiffon Dress</a>
                                            <p class="reating">
                                                            <span class="rate">
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                            </span>
                                            </p>
                                            <p class="product-text">Faded short sleeves t-shirt with high neckline. Soft and stretchy material for a comfortable fit. Accessorize with a straw hat and you're ready for summer! </p>
                                            <span class="price">$16.40</span>
                                            <div class="featured-button">
                                                <a class="wishlist" href="wishlists.html"><i class="fa fa-heart"></i></a>
                                                <a class="fetu-comment" href="#"><i class="fa fa-signal"></i></a>
                                                <a class="add-to-card" href="cart.html"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End featured item -->
                                <!-- Start featured item -->
                                <div class="col-sm-12">
                                    <div class="featured-inner">
                                        <div class="featured-image">
                                            <a href="single-product.html">
                                                <img alt="" src="img/product/printed-chiffon-dress4.jpg">
                                            </a>
                                            <span class="price-percent-reduction">-20%</span>
                                        </div>
                                        <div class="featured-info">
                                            <a href="single-product.html">Printed Chiffon Dress</a>
                                            <p class="reating">
                                                            <span class="rate">
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                            </span>
                                            </p>
                                            <p class="product-text">Faded short sleeves t-shirt with high neckline. Soft and stretchy material for a comfortable fit. Accessorize with a straw hat and you're ready for summer! </p>
                                            <span class="price">$16.40</span>
                                            <div class="featured-button">
                                                <a class="wishlist" href="wishlists.html"><i class="fa fa-heart"></i></a>
                                                <a class="fetu-comment" href="#"><i class="fa fa-signal"></i></a>
                                                <a class="add-to-card" href="cart.html"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End featured item -->
                                <!-- Start featured item -->
                                <div class="col-sm-12">
                                    <div class="featured-inner">
                                        <div class="featured-image">
                                            <a href="single-product.html">
                                                <img alt="" src="img/product/printed-chiffon-dress8.jpg">
                                            </a>
                                            <span class="price-percent-reduction">-20%</span>
                                        </div>
                                        <div class="featured-info">
                                            <a href="single-product.html">Printed Chiffon Dress</a>
                                            <p class="reating">
                                                            <span class="rate">
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                            </span>
                                            </p>
                                            <p class="product-text">Faded short sleeves t-shirt with high neckline. Soft and stretchy material for a comfortable fit. Accessorize with a straw hat and you're ready for summer! </p>
                                            <span class="price">$16.40</span>
                                            <div class="featured-button">
                                                <a class="wishlist" href="wishlists.html"><i class="fa fa-heart"></i></a>
                                                <a class="fetu-comment" href="#"><i class="fa fa-signal"></i></a>
                                                <a class="add-to-card" href="cart.html"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End featured item -->
                                <!-- Start featured item -->
                                <div class="col-sm-12">
                                    <div class="featured-inner">
                                        <div class="featured-image">
                                            <a href="single-product.html">
                                                <img alt="" src="img/product/printed-chiffon-dress5.jpg">
                                            </a>
                                            <span class="price-percent-reduction">-20%</span>
                                        </div>
                                        <div class="featured-info">
                                            <a href="single-product.html">Printed Chiffon Dress</a>
                                            <p class="reating">
                                                            <span class="rate">
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                            </span>
                                            </p>
                                            <p class="product-text">Faded short sleeves t-shirt with high neckline. Soft and stretchy material for a comfortable fit. Accessorize with a straw hat and you're ready for summer! </p>
                                            <span class="price">$306.40</span>
                                            <div class="featured-button">
                                                <a class="wishlist" href="wishlists.html"><i class="fa fa-heart"></i></a>
                                                <a class="fetu-comment" href="#"><i class="fa fa-signal"></i></a>
                                                <a class="add-to-card" href="cart.html"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End featured item -->
                                <!-- Start featured item -->
                                <div class="col-sm-12">
                                    <div class="featured-inner">
                                        <div class="featured-image">
                                            <a href="single-product.html">
                                                <img alt="" src="img/product/printed-chiffon-dress3.jpg">
                                            </a>
                                            <span class="price-percent-reduction">-20%</span>
                                        </div>
                                        <div class="featured-info">
                                            <a href="single-product.html">Printed Chiffon Dress</a>
                                            <p class="reating">
                                                            <span class="rate">
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                            </span>
                                            </p>
                                            <p class="product-text">Faded short sleeves t-shirt with high neckline. Soft and stretchy material for a comfortable fit. Accessorize with a straw hat and you're ready for summer! </p>
                                            <span class="price">$26.40</span>
                                            <div class="featured-button">
                                                <a class="wishlist" href="wishlists.html"><i class="fa fa-heart"></i></a>
                                                <a class="fetu-comment" href="#"><i class="fa fa-signal"></i></a>
                                                <a class="add-to-card" href="cart.html"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End featured item -->
                                <!-- Start featured item -->
                                <div class="col-sm-12">
                                    <div class="featured-inner">
                                        <div class="featured-image">
                                            <a href="single-product.html">
                                                <img alt="" src="img/product/printed-chiffon-dresst.jpg">
                                            </a>
                                            <span class="price-percent-reduction">-20%</span>
                                        </div>
                                        <div class="featured-info">
                                            <a href="single-product.html">Printed Chiffon Dress</a>
                                            <p class="reating">
                                                            <span class="rate">
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                                <i class="fa fa-star"></i>
                                                            </span>
                                            </p>
                                            <p class="product-text">Faded short sleeves t-shirt with high neckline. Soft and stretchy material for a comfortable fit. Accessorize with a straw hat and you're ready for summer! </p>
                                            <span class="price">$26.40</span>
                                            <div class="featured-button">
                                                <a class="wishlist" href="wishlists.html"><i class="fa fa-heart"></i></a>
                                                <a class="fetu-comment" href="#"><i class="fa fa-signal"></i></a>
                                                <a class="add-to-card" href="cart.html"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End featured item -->
                            </div>
                        </div>
                        <!-- Start categori show item -->
                        <div class="categori-show-item">
                            <div class="cat-show-item">
                                <p>Showing 1 - 8 of 8 items</p>
                            </div>
                            <div class="cat-show-button">
                                <a href="#" class="cat-button"><span>Compare(0)<i class="fa fa-angle-right"></i></span></a>
                            </div>
                        </div>
                        <!-- End categori show item -->
                    </div>
                </div>
                <!-- Start categori content -->
            </div>
        </div>
    </div>
    <!-- End shop area -->
</div>


<?php $this->partial("partials/brands"); ?>

<?php $this->partial("partials/blogs"); ?>