<div id="shopify-section-product-page" class="shopify-section reload-product-page mount-overlay"><article id="product-page" class="loading" itemscope itemtype="//schema.org/Product" data-collection="all">

        <meta itemprop="url" content="http://king-theme.myshopify.com/products/unicon-test-short-sleeve">
        <meta itemprop="image" content="//cdn.shopify.com/s/files/1/0691/8855/products/2_grande.jpg?v=1455787064">

        <div id="product-content" class="clearfix">

            <header id="product-header">




                <nav id="breadcrumb" role="navigation" aria-label="breadcrumbs">

                    <a href="/">Главная</a>




                    <span aria-hidden="true">/</span>


                    <a href="/shoes/index" title="">Магазин</a>



                    <span aria-hidden="true">/</span>
                    <span><?=$shoes->name?></span>



                </nav>





                <h1 itemprop="name"><?=$shoes->name?></h1>


                <p id="product-vendor" itemprop="brand"><?=$shoes->article?></p>
			

			<span id="price">
				<span id="productPrice"><?=$shoes->price?> грн.</span>
				
			</span>

            </header>

            <section id="product-description">


                <style type="text/css">
                    #product-content div[itemprop="description"] > div {
                        height: 123px;
                        overflow: hidden;
                    }
                </style>


                <div itemprop="description">
                    <div>
                        <p><span class="fbPhotosPhotoCaption" aria-live="polite" data-ft='{"tn":"K"}' id="fbPhotoSnowliftCaption" tabindex="0"><span class="hasCaption">
                                    <?php
                                    $attributes = array();
                                    foreach($shoes->attributes as $attribute){
                                        if(empty($attributes[$attribute->group->name])){
                                            $attributes[$attribute->group->name] = array();
                                        }
                                        $attributes[$attribute->group->name][] = $attribute->name;
                                    }
                                    mb_internal_encoding('UTF-8');
                                    ?>
                                    <strong>Артикул:</strong> <?=$shoes->article?><br />
                                    <?php foreach($attributes as $name => $values):?>
                                        <strong><?=$name?>:</strong> <?=mb_strtolower(implode(', ', $values))?><br />
                                    <?php endforeach?>
                                    <?php echo $shoes->description->description?><br />
                                </span></span></p>
                    </div>
                </div>
                <br />
                <br />
                <div itemprop="offers" itemscope itemtype="//schema.org/Offer">



                    <meta itemprop="price" content="USD">
                    <meta itemprop="priceCurrency" content="18700">

                    <link itemprop="availability" href="//schema.org/InStock">

                    <form action="#" method="post" onsubmit="return false;" ">

                        <button type="submit" name="add" id="addToCart" class="button color" onclick="add_to_cart(); return false;"><span id="addToCartText">КУПИТЬ</span></button>



                    </form>

                </div>


            </section>

        </div>

        <section id="product-gallery" class="scale-up-fill">

            <style type="text/css">
                #product-gallery {
                    background: #f4f4f4;
                }
                #product-gallery  .swiper-container .swiper-slide {
                    background: #f4f4f4;
                }
            </style>



            <div class="swiper-container">

                <div id="home-slider" class="swiper-container" data-section-id="slideshow" data-transition="slide" data-autoplay="true" data-timer="7">

                    <div class="swiper-wrapper">

                        <?php foreach($shoes->images as $k => $image) : ?>

                        <div class="slide swiper-slide slide--1484211369679"  data-index="1">

                            <div class="slide-img image" style="background-image:url(<?=$image->originalURL()?>)">
                                <img src="<?=$image->originalURL()?> " alt="" />


                            </div>



                        </div>
                        <?php endforeach?>

                    </div>

                    <!--div class="draw-buttons gal three" aria-hidden="true">
                        <div class="holder">
                            <span class="swiper-no"><span class="cur">1</span><span class="tot">1</span></span>
	      <span class="btn-prev">

	<svg version="1.1" class="svg left" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="60px" height="60px" viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve"><g><path d="M24.294,33.641c-0.908-0.991-1.694-1.745-2.357-2.261c-0.663-0.517-1.289-0.901-1.877-1.154v-0.461c0.677-0.329,1.333-0.748,1.969-1.256c0.635-0.51,1.395-1.257,2.276-2.242h0.79c-0.643,1.375-1.316,2.431-2.021,3.169l16.355,0v1.036l-16.355,0c0.52,0.657,0.882,1.147,1.086,1.471c0.206,0.325,0.51,0.891,0.912,1.697H24.294z"/></g></svg>
<a href="#" class="swiper-prev"></a></span>
	      <span class="btn-next">

	<svg version="1.1" class="svg right" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="60px" height="60px" viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve"><g><path d="M35.195,26.268c0.908,0.991,1.694,1.745,2.357,2.261c0.663,0.517,1.289,0.901,1.877,1.154v0.461c-0.677,0.328-1.333,0.747-1.969,1.256c-0.636,0.51-1.395,1.257-2.276,2.241h-0.79c0.643-1.375,1.316-2.431,2.021-3.169H20.06v-1.036h16.355c-0.52-0.656-0.882-1.146-1.087-1.471s-0.51-0.891-0.912-1.697H35.195z"/></g></svg>
<a href="#" class="swiper-next"></a></span>
                        </div>
                    </div-->

                </div>

                <div class="swiper-pagination"></div>

            </div>



        </section>








        <!--nav class="draw-buttons nav three">

            <div class="holder">

					
						
						<span class="btn-prev">
							

	<svg version="1.1" class="svg left" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="60px" height="60px" viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve"><g><path d="M24.294,33.641c-0.908-0.991-1.694-1.745-2.357-2.261c-0.663-0.517-1.289-0.901-1.877-1.154v-0.461c0.677-0.329,1.333-0.748,1.969-1.256c0.635-0.51,1.395-1.257,2.276-2.242h0.79c-0.643,1.375-1.316,2.431-2.021,3.169l16.355,0v1.036l-16.355,0c0.52,0.657,0.882,1.147,1.086,1.471c0.206,0.325,0.51,0.891,0.912,1.697H24.294z"/></g></svg>

							<a href="/collections/all/products/louis-erard" title="">&larr;</a>
						</span>
					

					<span class="btn-close">
						<span class="back">
							

	<svg version="1.1" class="svg close" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="60px" height="60px" viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve"><polygon points="38.936,23.561 36.814,21.439 30.562,27.691 24.311,21.439 22.189,23.561 28.441,29.812   22.189,36.064 24.311,38.186 30.562,31.934 36.814,38.186 38.936,36.064 32.684,29.812 "/></svg>

							<a href="/collections/all"></a>
						</span>
						<span class="front">
							

	<svg version="1.1" class="svg grid" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="60px" height="60px" viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve"><rect x="35.75" y="20" width="5" height="5"/><rect x="27.75" y="20" width="5" height="5"/><rect x="19.75" y="20" width="5" height="5"/><rect x="35.75" y="28" width="5" height="5"/><rect x="27.75" y="28" width="5" height="5"/><rect x="19.75" y="28" width="5" height="5"/><rect x="35.75" y="36" width="5" height="5"/><rect x="27.75" y="36" width="5" height="5"/><rect x="19.75" y="36" width="5" height="5"/></svg>

						</span>
					</span>

					
						
						<span class="btn-next">
							

	<svg version="1.1" class="svg right" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="60px" height="60px" viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve"><g><path d="M35.195,26.268c0.908,0.991,1.694,1.745,2.357,2.261c0.663,0.517,1.289,0.901,1.877,1.154v0.461c-0.677,0.328-1.333,0.747-1.969,1.256c-0.636,0.51-1.395,1.257-2.276,2.241h-0.79c0.643-1.375,1.316-2.431,2.021-3.169H20.06v-1.036h16.355c-0.52-0.656-0.882-1.146-1.087-1.471s-0.51-0.891-0.912-1.697H35.195z"/></g></svg>

							<a href="/collections/all/products/maple-ipad-sleeve" title="">&rarr;</a>
						</span>


            </div>

        </nav-->





    </article>

    <div id="product-page-settings" data-truncated_description="true" data-truncated_description_lines="123" data-gallery_max_size="true" data-gallery_resizing="fill" data-gallery_transition="slide" data-gallery_autoplay="true" data-gallery_timer="6" data-gallery-posfix="false" data-zoom="false"></div>


</div>

