<div class="best-sellar-area featured-product-area">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12">
                <div class="area-title">
                    <h3>ЛУЧШИЙ ВЫБОР</h3>
                </div>
            </div>
            <div class="featured-product">
                <div class="featured-item">
                    <!-- Start featured item -->
                    <?php $promo = \Models\PromoBlocks::findFirst("const = '".\Models\PromoBlocks::BESTSELLER."'");?>
                    <?php foreach($promo->shoes as $shoes):?>
                    <div class="col-xs-12 col-sm-3">
                        <div class="featured-inner">
                            <div class="featured-image">
                                <a href="<?=$shoes->getURL()?>">
                                    <img src="<?=$shoes->mainImage->thumbnailURL(250, 250)?>" alt="">
                                </a>
                            </div>
                            <div class="featured-info">
                                <a href="<?=$shoes->getURL()?>"><?=$shoes->name?></a>
                                <span class="price"><?=$shoes->price?></span>
                                <div class="featured-button">
                                    <a href="#" class="add-to-card" data-shoes-id="<?=$shoes->id?>"><i class="fa fa-shopping-cart"></i>Купить</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- End featured item -->
                    <?php endforeach?>
                </div>
            </div>
        </div>
    </div>
</div>