
<div class="col-xs-12 col-sm-4 col-md-3">
    <div class="shop-categori-area">
        <div class="sidebar-menu-title">
            <h2><i class="fa fa-th-list"></i>Каталог</h2>
        </div>
        <div class="shop-categori">
            <div class="shop-categori-inner">
                <?php $groups = \Models\AttributesGroups::find()?>
                <?php foreach($groups as $group):?>
                <!-- Start Categori -->
                <div class="categoris categori-border">
                    <span class="cat-title"><?=$group->name?></span>
                    <ul>
                        <?php foreach($group->attributes as $attribute):?>
                            <?php
                                $filter_url = '/shoes/index?';
                                $filter_add = $filter_url;

                                foreach($filter as $key => $value) {
                                    if($key != $attribute->id){
                                        $filter_add .= 'filter['.$key.']='.$value.'&';
                                    }
                                }
                                $filter_remove = $filter_add;

                                $filter_add .= 'filter['.$attribute->id.']=1';
                            ?>
                        <li>
                            <span><input disabled="disabled" type="checkbox" class="checkbox" <?=!empty($filter[$attribute->id]) ? 'checked="checked"' : ''?> ></span>
                            <label>
                                <a href="<?=$filter_add?>"><?=$attribute->name?></a>
                                <?php if($filter[$attribute->id]):?>
                                    <a href="<?=$filter_remove?>">X</a>
                                <?php endif?>
                            </label>
                        </li>
                        <?php endforeach?>
                    </ul>
                </div>
                <?php endforeach?>

                </div>
                <!-- End Categori -->
            </div>
        </div>

    </div>
<!-- End shop categori area -->