<!-- Start shop categori area -->
<div class="col-xs-12 col-sm-4 col-md-3">
    <div class="shop-categori-area">
        <div class="sidebar-menu-title">
            <h2><i class="fa fa-th-list"></i>Catalog</h2>
        </div>
        <div class="shop-categori">
            <div class="shop-categori-inner">
                <!-- Start Categori -->
                <div class="categoris categori-border">
                    <span class="cat-title">Categories</span>
                    <ul>
                        <li>
                            <span><input type="checkbox" class="checkbox"></span>
                            <label>
                                <a href="">category 1<span> (17)</span></a>
                            </label>
                        </li>
                        <li>
                            <span><input type="checkbox" class="checkbox"></span>
                            <label>
                                <a href="">category 2<span> (17)</span></a>
                            </label>
                        </li>
                        <li>
                            <span><input type="checkbox" class="checkbox"></span>
                            <label>
                                <a href="">category 3<span> (17)</span></a>
                            </label>
                        </li>
                    </ul>
                </div>
                <!-- End Categori -->
                <!-- Start Categori -->
                <div class="categoris categori-border">
                    <span class="cat-title">Availability</span>
                    <ul>
                        <li>
                            <span><input type="checkbox" class="checkbox"></span>
                            <label>
                                <a href="">In stock<span> (17)</span></a>
                            </label>
                        </li>
                    </ul>
                </div>
                <!-- End Categori -->
                <!-- Start Categori -->
                <div class="categoris categori-border">
                    <span class="cat-title">Condition</span>
                    <ul>
                        <li>
                            <span><input type="checkbox" class="checkbox"></span>
                            <label>
                                <a href="">New<span> (17)</span></a>
                            </label>
                        </li>
                    </ul>
                </div>
                <!-- End Categori -->
                <!-- Start Categori -->
                <div class="categoris categori-border">
                    <span class="cat-title">Manufacturer</span>
                    <ul>
                        <li>
                            <span><input type="checkbox" class="checkbox"></span>
                            <label>
                                <a href="">Fashion Manufacturer<span> (17)</span></a>
                            </label>
                        </li>
                    </ul>
                </div>
                <!-- End Categori -->
                <!-- Start Categori -->
                <div class="categoris categori-border">
                    <span class="cat-title">Price</span>
                    <ul>
                        <li class="price-range">
                            <label for="amount">Range: <input type="text" style="border:0; color:#f6931f; font-weight:bold;" readonly="" id="amount"></label>
                            <div id="slider-range" class="ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all"><div class="ui-slider-range ui-widget-header ui-corner-all" style="left: 0%; width: 80%;"></div><span tabindex="0" class="ui-slider-handle ui-state-default ui-corner-all" style="left: 0%;"></span><span tabindex="0" class="ui-slider-handle ui-state-default ui-corner-all" style="left: 80%;"></span></div>
                        </li>
                    </ul>
                </div>
                <!-- End Categori -->
                <!-- Start Categori -->
                <div class="categoris categori-border">
                    <span class="cat-title">Size</span>
                    <ul>
                        <li>
                            <span><input type="checkbox" class="checkbox"></span>
                            <label>
                                <a href="">S<span> (17)</span></a>
                            </label>
                        </li>
                        <li>
                            <span><input type="checkbox" class="checkbox"></span>
                            <label>
                                <a href="">M<span> (17)</span></a>
                            </label>
                        </li>
                        <li>
                            <span><input type="checkbox" class="checkbox"></span>
                            <label>
                                <a href="">L<span> (17)</span></a>
                            </label>
                        </li>
                    </ul>
                </div>
                <!-- End Categori -->
                <!-- Start Categori -->
                <div class="categoris categori-border">
                    <span class="cat-title">Compositions</span>
                    <ul>
                        <li>
                            <span><input type="checkbox" class="checkbox"></span>
                            <label>
                                <a href="">Cotton<span> (3)</span></a>
                            </label>
                        </li>
                        <li>
                            <span><input type="checkbox" class="checkbox"></span>
                            <label>
                                <a href="">Polyester<span> (12)</span></a>
                            </label>
                        </li>
                        <li>
                            <span><input type="checkbox" class="checkbox"></span>
                            <label>
                                <a href="">Viscose<span> (2)</span></a>
                            </label>
                        </li>
                    </ul>
                </div>
                <!-- End Categori -->
                <!-- Start Categori -->
                <div class="categoris categori-border">
                    <span class="cat-title">Styles</span>
                    <ul>
                        <li>
                            <span><input type="checkbox" class="checkbox"></span>
                            <label>
                                <a href="">Casual<span> (3)</span></a>
                            </label>
                        </li>
                        <li>
                            <span><input type="checkbox" class="checkbox"></span>
                            <label>
                                <a href="">Dressy<span> (1)</span></a>
                            </label>
                        </li>
                        <li>
                            <span><input type="checkbox" class="checkbox"></span>
                            <label>
                                <a href="">Girly<span> (13)</span></a>
                            </label>
                        </li>
                    </ul>
                </div>
                <!-- End Categori -->
                <!-- Start Categori -->
                <div class="categoris categori-border">
                    <span class="cat-title">Properties</span>
                    <ul>
                        <li>
                            <span><input type="checkbox" class="checkbox"></span>
                            <label>
                                <a href="">Colorful Dress<span> (1)</span></a>
                            </label>
                        </li>
                        <li>
                            <span><input type="checkbox" class="checkbox"></span>
                            <label>
                                <a href="">Maxi Dress<span> (1)</span></a>
                            </label>
                        </li>
                        <li>
                            <span><input type="checkbox" class="checkbox"></span>
                            <label>
                                <a href="">Midi Dress<span> (11)</span></a>
                            </label>
                        </li>
                        <li>
                            <span><input type="checkbox" class="checkbox"></span>
                            <label>
                                <a href="">Short Dress<span> (2)</span></a>
                            </label>
                        </li>
                        <li>
                            <span><input type="checkbox" class="checkbox"></span>
                            <label>
                                <a href="">Short Sleeve<span> (2)</span></a>
                            </label>
                        </li>
                    </ul>
                </div>
                <!-- End Categori -->
            </div>
        </div>
        <div class="tag-area">
            <h2 class="tag-title">Tags</h2>
            <div class="tags">
                <a href="#">camera</a>
                <a href="#">mobile</a>
                <a href="#">electronic</a>
                <a href="#">destop</a>
                <a href="#">tablet</a>
                <a href="#">accessories</a>
                <a href="#">camcorder</a>
                <a href="#">laptop</a>
            </div>
        </div>
    </div>
</div>
<!-- End shop categori area -->