<?php
    function shoes_index_filter_url($attribute)
    {

    }

?>
<div class="col-xs-12 col-sm-4 col-md-3">
    <div class="shop-categori-area">
        <div class="sidebar-menu-title">
            <h2><i class="fa fa-th-list"></i>Каталог</h2>
        </div>
        <div class="shop-categori">
            <div class="shop-categori-inner">
                <?php $groups = \Models\AttributesGroups::find()?>
                <?php foreach($groups as $group):?>
                <!-- Start Categori -->
                <div class="categoris categori-border">
                    <span class="cat-title"><?=$group->name?></span>
                    <ul>
                        <?php foreach($group->attibutes as $attribute):?>
                            <?php
                                $filter_url = '/shoes/index?';
                                $filter_add = $filter_remove = $filter_url;
                                foreach($filter as $key => $value) {
                                    $filter_add .= $key.'='.$value.'&';
                                    if($key != $attribute->id){
                                        $filter_remove .= $key.'='.$value.'&';
                                    }
                                }
                            ?>
                        <li>
                            <span><input type="checkbox" class="checkbox"></span>
                            <label>
                                <a href="<?=$filter_add?>"><?=$attribute->name?></a>&nbsp;<a href="<?=$filter_remove?>"><?=$attribute->name?>X</a>
                            </label>
                        </li>
                        <?php endforeach?>
                    </ul>
                </div>
                <?php endforeach?>

                </div>
                <!-- End Categori -->
            </div>
        </div>
        
    </div>
</div>
<!-- End shop categori area -->