<div class="featured-product-area">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12">
                <div class="area-title">
                    <h3>Акции</h3>
                </div>
            </div>
            <div class="featured-product">
                <?php $promo = \Models\PromoBlocks::findFirst("const = '".\Models\PromoBlocks::FEATURED."'");?>
                <?php foreach($promo->shoes as $shoes):?>
                <div class="featured-item">
                    <!-- Start featured item -->
                    <div class="col-sm-3">
                        <div class="featured-inner">
                            <div class="featured-image">
                                <a href="single-product.html">
                                    <img src="<?=$shoes->mainImage->thumbnailURL(250, 250)?>" alt="">
                                </a>
                            </div>
                            <div class="featured-info">
                                <a href="single-product.html"><?=$shoes->name?></a>

                                <span class="price"><?=$shoes->price?></span>
                                <div class="featured-button">
                                    <a href="cart.html" class="add-to-card"><i class="fa fa-shopping-cart"></i>Купить</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- End featured item -->
                    <?php endforeach?>
                </div>
            </div>
        </div>
    </div>
</div>