<div class="col-xs-12 col-sm-12 col-md-3">
    <div class="categori-slide-product">
        <div class="slide-product-title">
            <h3>Распродажа</h3>
        </div>

        <?php $promo = \Models\PromoBlocks::findFirst("const = '".\Models\PromoBlocks::SALE_OFF."'");
        $shoes = $promo->shoes;

        ?>

        <div class="slide-product">
            <?php for($i = 1; $i <= 4; $i++):?>
            <div class="slide-product-item">
                <?php for($j=1; $j<=3; $j++):?>
                    <?php $sh = $shoes[$i*$j]?>
                <div class="item3">
                    <div class="product-image">
                        <a href="single-product.html">
                            <img src="img/product-mini/printed-summer-dress1.jpg" alt="">
                        </a>
                        <span class="price-percent-reduction">-5%</span>
                    </div>
                    <div class="product-info">
                        <a href="single-product.html"><?=$sh->name?></a>
                    </div>
                </div>
                <?php endfor?>
            </div>
            <?php endfor?>

        </div>
    </div>
</div>