<div class="col-xs-12 col-sm-12 col-md-3">
    <div class="categori-slide-product">
        <div class="slide-product-title">
            <h3>Распродажа</h3>
        </div>

        <?php $promo = \Models\PromoBlocks::findFirst("const = '".\Models\PromoBlocks::SALE_OFF."'");
        $shoes = $promo->shoes;
        $shoes->next();

        ?>

        <div class="slide-product">
            <?php for($i = 1; $i <= 4; $i++):?>
            <div class="slide-product-item">
                <?php for($j=1; $j<=3; $j++):?>
                    <?php $sh = $shoes->current()?>
                <div class="item3">
                    <div class="product-image">
                        <a href="/shoes/view/<?=$sh->id?>">
                            <img src="<?=$sh->mainImage->thumbnailURL(125, 125)?>" alt="">
                        </a>
                        <span class="price-percent-reduction"><?=$sh->price?> грн.</span>
                    </div>
                    <div class="product-info">
                        <a href="/shoes/view/<?=$sh->id?>"><?=$sh->name?></a>
                    </div>
                </div>
                    <?php $shoes->next();?>
                <?php endfor?>
            </div>
            <?php endfor?>

        </div>
    </div>
</div>