<?php

$group = \Models\AttributesGroups::findFirstByConst(\Models\AttributesGroups::TYPE);
?>
<!-- Start categori menu -->
<div class="col-xs-12 col-sm-4 col-md-3">
    <div class="categori-menu">
        <div class="sidebar-menu-title">
            <h2><i class="fa fa-th-list"></i>Категории</h2>
        </div>
        <div class="sidebar-menu">
            <ul>
                <?php foreach($group->attributes as $attribute):?>
                    <li><a href="shop-grid.html" class="single-menu"><?=$attribute->name?></a></li>
                <?php endforeach?>
            </ul>
        </div>
    </div>
</div>
<!-- End categori menu -->
