<?php

$categories = Models\Categories::query()
    ->where("parent_id = :parent_id:")
    //->andWhere("year < 2000")
    ->bind(array("parent_id" => CATEGORIES_TYPE_ID))
    ->order("order_number")
    ->execute();
?>
<!-- Start categori menu -->
<div class="col-xs-12 col-sm-4 col-md-3">
    <div class="categori-menu">
        <div class="sidebar-menu-title">
            <h2><i class="fa fa-th-list"></i>Категории</h2>
        </div>
        <div class="sidebar-menu">
            <ul>
                <?php foreach($categories as $category):?>
                    <li><a href="shop-grid.html" class="single-menu"><?=$category->name?></a></li>
                <?php endforeach?>
            </ul>
        </div>
    </div>
</div>
<!-- End categori menu -->
