<p>&nbsp</p>
<!--div class="brand-and-client">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="area-title">
                    <h3>BRAND & CLIENTS</h3>
                </div>
            </div>
            <div class="col-sm-12">
                <div class="brand-logo featured-product-area">
                    <div class="clients">
                        <a href="#"><img src="/img/brand-logo/1.jpg" alt=""></a>
                    </div>
                    <div class="clients">
                        <a href="#"><img src="/img/brand-logo/2.jpg" alt=""></a>
                    </div>
                    <div class="clients">
                        <a href="#"><img src="/img/brand-logo/3.jpg" alt=""></a>
                    </div>
                    <div class="clients">
                        <a href="#"><img src="/img/brand-logo/4.jpg" alt=""></a>
                    </div>
                    <div class="clients">
                        <a href="#"><img src="/img/brand-logo/5.jpg" alt=""></a>
                    </div>
                    <div class="clients">
                        <a href="#"><img src="/img/brand-logo/6.jpg" alt=""></a>
                    </div>
                    <div class="clients">
                        <a href="#"><img src="/img/brand-logo/1.jpg" alt=""></a>
                    </div>
                    <div class="clients">
                        <a href="#"><img src="/img/brand-logo/3.jpg" alt=""></a>
                    </div>
                    <div class="clients">
                        <a href="#"><img src="/img/brand-logo/4.jpg" alt=""></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div-->