<aside id="footer" class="loading">
    <div class="social-icons">


        <a href="#">#<i class="fa fa-twitter fa-fw"></i></a>



        <a href="#">#<i class="fa fa-facebook fa-fw"></i></a>







        <a href="#">#<i class="fa fa-vimeo-square fa-fw"></i></a>









        <a href="#">#<i class="fa fa-linkedin fa-fw"></i></a>






    </div>




    <p>Copyright &copy; 2017 <a href="/">King </a></p>
    <p><a target="_blank" rel="nofollow" href="https://www.shopify.com">Powered by Shopify</a></p>
</aside>