<?php
$group = \Models\AttributesGroups::findFirstByConst(\Models\AttributesGroups::TYPE);
?>
<nav id="menu" role="navigation">
    <div>
        <ul class="top-menu collections-menu size-10">
            <?php foreach($group->attributes as $attribute):?>
            <li>
                <a href="/redesign/shoes/index?filter[<?=$attribute->id?>]=1"><?=$attribute->name?></a>
            </li>
            <?php endforeach?>
        </ul>

        <ul class="top-menu size-2">










            <li class="submenu selected" aria-haspopup="true">
                <a href="/">
                    Categories


                    <svg version="1.0" class="svg arrow" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="7px" height="4px" viewBox="0 0 7 4" enable-background="new 0 0 7 4" xml:space="preserve"><polygon points="7.006,-0.044 3.5,3.961 -0.006,-0.044 "/></svg>

                </a>
                <ul class="sub-menu">

                    <li><a href="/collections/shirts">Shirts</a></li>

                    <li><a href="/collections/shorts">Shorts</a></li>

                    <li><a href="/collections/sweatshirt">Hoodies</a></li>

                    <li><a href="/collections/hats">Hats</a></li>

                    <li class="selected"><a href="/">Accessories</a></li>

                </ul>
            </li>









            <li>
                <a href="/collections/about-us">About Us</a>
            </li>







        </ul>
    </div>
    <a class="responsive-close" href="#">

        <svg version="1.1" class="svg close" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="60px" height="60px" viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve"><polygon points="38.936,23.561 36.814,21.439 30.562,27.691 24.311,21.439 22.189,23.561 28.441,29.812   22.189,36.064 24.311,38.186 30.562,31.934 36.814,38.186 38.936,36.064 32.684,29.812 "/></svg>
    </a>
</nav>
