<nav role="navigation" id="menu">
    <div>
        <ul class="top-menu collections-menu size-1">
            <li aria-haspopup="true" class="submenu">
                <ul style="display: block; overflow: visible;" class="sub-menu">

                    <li><a href="/shoes/index">Все коллекции</a></li>
                    <li><a href="/shoes/index?filter[22]=1">Босоножки</a></li>
                    <li><a href="/shoes/index?filter[23]=1">Туфли</a></li>
                    <li><a href="/shoes/index?filter[24]=1">Шлепки</a></li>
                    <li><a href="/shoes/index?filter[26]=1">Сапоги</a></li>
                    <li><a href="/shoes/index?filter[29]=1">Ботинки</a></li>
                </ul>
            </li>
        </ul>
        <!--ul class="top-menu size-4">
            <li>
                <a href="/pages/about-us">About Us</a>
            </li>
        </ul-->
    </div>
</nav>