<!doctype html>
<!--[if lt IE 8]><html class="no-js ie7" lang="en"> <![endif]-->
<!--[if IE 8]><html class="no-js ie8" lang="en"> <![endif]-->
<!--[if (gt IE 8)|!(IE)]><!--> <html class="no-js"> <!--<![endif]-->
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">


    <title><?=!empty($title_for_page) ? $title_for_page : 'RUMI | Обувь в наличии и под заказ'?></title>
    <meta name="description" content="<?=!empty($meta_description) ? $meta_description : 'Купить обувь в Днепропетровске в наличии и под заказ'?>" />
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <?php if(!empty($og_url)):?>
        <meta property="og:url"           content="<?=$og_url?>" />
    <?php endif?>
    <meta property="og:type"          content="website" />
    <?php if(!empty($og_url)):?>
        <meta $og_title="og:title"         content="<?=$og_title?>" />
    <?php endif?>
    <?php if(!empty($og_description)):?>
        <meta property="og:description"   content="<?=$og_description?>" />
    <?php endif?>
    <?php if(!empty($og_image)):?>
        <meta property="og:image"         content="<?=$og_image?>" />
    <?php endif?>

    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" media="all" />
    <link href="/redesign/css/main.css?asdasda" rel="stylesheet" type="text/css" media="all" />

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js" type="text/javascript"></script>
    <script src="/js/sweetalert.min.js"></script>
    <link href="//fonts.googleapis.com/css?family=Montserrat:400,400italic,500,600,700,700italic" rel="stylesheet" type="text/css">
    <link href="//fonts.googleapis.com/css?family=Raleway:400,400italic,500,600,700,700italic" rel="stylesheet" type="text/css">
    <link href="//fonts.googleapis.com/css?family=Arvo:400,400italic,700" rel="stylesheet" type="text/css">

    <script type="text/javascript">
        function add_to_cart(){
            swal("Отличный выбор!", "Телефон для заказа: (050) 142-22-68", "success");
        }
    </script>

    <!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!--[if lt IE 10]>
    <script src="/redesign/js/js_placeholder.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        jQuery(document).ready(function(){
            $('input, textarea').placeholder();
        });
    </script>
    <![endif]-->

</head>

<body id="king" class="template-index no-touch clearfix">

<div id="shopify-section-sidebar" class="shopify-section mount-sidebar mount-overlay">
    <div id="sidebar-holder">
        <div id="sidebar">
            <div style="flex: 1 0 auto;">
                <header id="logo">
                    <h1 itemscope itemtype="//schema.org/Organization">
                        <a class="logo-img" href="/" itemprop="url">
                            <img src="/redesign/img/logo.png" alt="RUMI" style="max-width: 110px;" />
                        </a>
                    </h1>
                </header>

                <?php $this->partial("partials/meta"); ?>
                <?php $this->partial("partials/menu"); ?>
            </div>
            <?php $this->partial("partials/footer"); ?>
        </div>
    </div>
</div>

<div id="content-holder">

    <main id="content" role="main">

        <div id="page-content">
            <?php echo $this->getContent(); ?>
        </div>
    </main>
</div>


<div id="main-overlay" style="display: none;">

    <div id="cart-overlay" class="table-display opened" style="visibility: visible; opacity: 1; top: 0px;">
        <div>
            <div class="simple-overlay-box">
                <svg version="1.1" class="svg check" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" xml:space="preserve" x="0px" y="0px" width="111px" height="80px" viewBox="0 0 111 80"><g><path d="M 108.9767 10.3015 L 41.8015 77.4767 C 41.4479 77.8303 41.0494 78.1039 40.6354 78.3411 C 38.4844 79.9092 35.4622 79.7404 33.5209 77.799 L 1.701 45.9792 C -0.4468 43.8313 -0.4468 40.3489 1.701 38.201 C 3.8489 36.0532 7.3314 36.0532 9.4792 38.201 L 37.5 66.2218 L 101.1985 2.5234 C 103.3464 0.3755 106.8289 0.3755 108.9767 2.5234 C 111.1246 4.6712 111.1246 8.1537 108.9767 10.3015 Z"></path></g></svg>

                <a href="#" onclick="return false;">Отличный выбор!</a>
                <hr>
                <a href="#" onclick="$('#main-overlay').find('.close').trigger('click');return false;">Телефон для заказа: (050) 872-46-98</a>

                <a href="#" class="close main">

                    <svg version="1.1" class="svg close" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="60px" height="60px" viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve"><polygon points="38.936,23.561 36.814,21.439 30.562,27.691 24.311,21.439 22.189,23.561 28.441,29.812   22.189,36.064 24.311,38.186 30.562,31.934 36.814,38.186 38.936,36.064 32.684,29.812 "></polygon></svg>
                </a>

            </div>
        </div>
    </div>





    </div>

</div>

<script type="text/javascript">

    // Saving theme settings and local translations as global variables

    jQuery.themeSettings = {
        cart_action: "overlay"
    }

    jQuery.themeWords = {
        products_page_share_text: "Spread the word",
        products_page_more_description_label: "Show more",
        products_page_less_description_label: "Show less"
    }





    jQuery.themeAssets = {
        arrowLeft: '<svg version="1.1" class="svg left" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="60px" height="60px" viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve"><g><path d="M24.294,33.641c-0.908-0.991-1.694-1.745-2.357-2.261c-0.663-0.517-1.289-0.901-1.877-1.154v-0.461c0.677-0.329,1.333-0.748,1.969-1.256c0.635-0.51,1.395-1.257,2.276-2.242h0.79c-0.643,1.375-1.316,2.431-2.021,3.169l16.355,0v1.036l-16.355,0c0.52,0.657,0.882,1.147,1.086,1.471c0.206,0.325,0.51,0.891,0.912,1.697H24.294z"/></g></svg>',
        arrowRight: '<svg version="1.1" class="svg right" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="60px" height="60px" viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve"><g><path d="M35.195,26.268c0.908,0.991,1.694,1.745,2.357,2.261c0.663,0.517,1.289,0.901,1.877,1.154v0.461c-0.677,0.328-1.333,0.747-1.969,1.256c-0.636,0.51-1.395,1.257-2.276,2.241h-0.79c0.643-1.375,1.316-2.431,2.021-3.169H20.06v-1.036h16.355c-0.52-0.656-0.882-1.146-1.087-1.471s-0.51-0.891-0.912-1.697H35.195z"/></g></svg>',
        arrowDown: '<svg version="1.0" class="svg arrow" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="7px" height="4px" viewBox="0 0 7 4" enable-background="new 0 0 7 4" xml:space="preserve"><polygon points="7.006,-0.044 3.5,3.961 -0.006,-0.044 "/></svg>',
        mgnpop: "//cdn.shopify.com/s/files/1/0691/8855/t/14/assets/js_magnific.popup.min.js?5446409592219251106"
    }

</script>

<script src="/redesign/js/js_plugins.min.js" type="text/javascript"></script>
<script src="/redesign/js/js_scripts.min.js" type="text/javascript"></script>

<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-78074422-2', 'auto');
    ga('send', 'pageview');

</script>

</body>
</html>
