    <div id="products-grid" class="border-true tiny loaded" style="width: 1151px; position: relative; height: 4887px;">
        <?php foreach($shoes->items as $item):?>
        <?php
        if($filter) {
            foreach ($filter as $attribute_id => $v) {
                if (!$item->hasAttributeId($attribute_id)) {
                    continue 2;
                }
            }
        }
        ?>
        <a href="<?=$item->getURL()?>" class="grid-item two light" style="width: 383px; position: absolute; left: 0px; top: 0px;">
            <img src="<?=$shoes->MainImage->originalURL()?>" alt="NYC" style="opacity: 1;">
            <div class="caption">
                <div>

                    <h2><?=$item->name?></h2>

                    <div class="price">

                        <strong><?=$item->price?> грн.</strong>


                    </div>

                </div>


            </div>




        </a>
        <?php endforeach?>
    </div>


    <!--div class="infobar bottom"><ul class="main-pagination">






            <li class="active"><span>1</span></li>




            <li><a href="/collections/shirts?page=2" title="">2</a></li>



            <li><a href="/collections/shirts?page=3" title="">3</a></li>



            <li><a href="/collections/shirts?page=4" title="">4</a></li>




            <li class="arrow"><a href="/collections/shirts?page=2" title="Next »">→</a></li>


        </ul></div-->


