<div id="shopify-section-product-page" class="shopify-section reload-product-page mount-overlay"><article id="product-page" class="loading" itemscope itemtype="//schema.org/Product" data-collection="all">

        <meta itemprop="url" content="http://king-theme.myshopify.com/products/unicon-test-short-sleeve">
        <meta itemprop="image" content="//cdn.shopify.com/s/files/1/0691/8855/products/2_grande.jpg?v=1455787064">

        <div id="product-content" class="clearfix">

            <header id="product-header">




                <nav id="breadcrumb" role="navigation" aria-label="breadcrumbs">

                    <a href="/">Главная</a>




                    <span aria-hidden="true">/</span>


                    <a href="/shoes/index" title="">Все Коллекции</a>



                    <span aria-hidden="true">/</span>
                    <span><?=$shoes->name?></span>



                </nav>





                <h1 itemprop="name"><?=$shoes->name?></h1>


                <p id="product-vendor" itemprop="brand"><?=$shoes->article?></p>
			

			<span id="price">
				<span id="productPrice"><?=$shoes->price?> грн.</span>
				
			</span>

            </header>

            <section id="product-description">


                <style type="text/css">
                    #product-content div[itemprop="description"] > div {
                        height: 123px;
                        overflow: hidden;
                    }
                </style>


                <div itemprop="description">
                    <div>
                        <p><span class="fbPhotosPhotoCaption" aria-live="polite" data-ft='{"tn":"K"}' id="fbPhotoSnowliftCaption" tabindex="0"><span class="hasCaption">One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections.</span></span></p>
                    </div>
                </div>

                <div itemprop="offers" itemscope itemtype="//schema.org/Offer">



                    <meta itemprop="price" content="USD">
                    <meta itemprop="priceCurrency" content="18700">

                    <link itemprop="availability" href="//schema.org/InStock">

                    <form action="/cart/add.js" method="post" enctype="multipart/form-data" id="add-to-cart">


                        <div class="product-variant selector-wrapper">
                            <label class="hidden">Color</label>
                            <select class="product-variants">

                                <option selected>
                                    Dark Grey
                                </option>

                                <option >
                                    Sky Blue
                                </option>

                            </select>
                        </div>


                        <select id="productSelect" name="id" class="styled" style="display: none !important">


                            <option  selected="selected"  value="974521877">
                                Dark Grey
                            </option>



                            <option  value="993985765">
                                Sky Blue
                            </option>


                        </select>


                        <input type="number" id="quantity" name="quantity" value="1" min="1" class="quantity-selector">


                        <button type="submit" name="add" id="addToCart" class="button color"><span id="addToCartText">Add to cart</span></button>


                        <a id="ajaxCartButton" class="overlay-button hidden" data-overlay="#cart-overlay" aria-hidden="true"></a>


                        <span id="variantQuantity" class="variant-quantity"></span>

                    </form>

                </div>

                <a href="#" id="share-link" class="overlay-button" data-overlay="#share-overlay">

                    <svg version="1.0" class="svg share" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="20px" height="20px" viewBox="0 0 20 20" enable-background="new 0 0 20 20" xml:space="preserve"><path d="M15.278,12.512c-0.806,0-1.538,0.309-2.09,0.812L7.241,10.29c0.023-0.154,0.04-0.312,0.04-0.474c0-0.091-0.006-0.18-0.014-0.27l6.004-3.061c0.542,0.458,1.242,0.736,2.008,0.736c1.718,0,3.111-1.393,3.111-3.111S16.996,1,15.278,1c-1.719,0-3.111,1.393-3.111,3.111c0,0.095,0.006,0.188,0.015,0.281L6.185,7.449C5.642,6.986,4.939,6.706,4.169,6.706c-1.718,0-3.111,1.393-3.111,3.11c0,1.719,1.393,3.111,3.111,3.111c0.693,0,1.331-0.229,1.847-0.612l6.159,3.14c-0.003,0.056-0.009,0.111-0.009,0.167c0,1.719,1.393,3.111,3.111,3.111c1.718,0,3.111-1.393,3.111-3.111C18.39,13.905,16.996,12.512,15.278,12.512z"/></svg>
                    Share this</a>

            </section>

        </div>

        <section id="product-gallery-" class="scale-up-fill">

            <style type="text/css">
                #product-gallery {
                    background: #f4f4f4;
                }
                #product-gallery  .swiper-container .swiper-slide {
                    background: #f4f4f4;
                }
            </style>



            <div class="swiper-container">

                <div id="home-slider" class="swiper-container" data-section-id="slideshow" data-transition="slide" data-autoplay="true" data-timer="7">

                    <div class="swiper-wrapper">

                        <?php foreach($shoes->images as $k => $image) : ?>

                        <div class="slide swiper-slide slide--1484211369679"  data-index="1">

                            <div class="slide-img image" style="background-image:url(<?=$image->originalURL()?>)">
                                <img src="<?=$image->originalURL()?> " alt="" />


                            </div>



                        </div>
                        <?php endforeach?>

                    </div>

                    <div class="draw-buttons gal three" aria-hidden="true">
                        <div class="holder">
                            <span class="swiper-no"><span class="cur">1</span><span class="tot">1</span></span>
	      <span class="btn-prev">

	<svg version="1.1" class="svg left" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="60px" height="60px" viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve"><g><path d="M24.294,33.641c-0.908-0.991-1.694-1.745-2.357-2.261c-0.663-0.517-1.289-0.901-1.877-1.154v-0.461c0.677-0.329,1.333-0.748,1.969-1.256c0.635-0.51,1.395-1.257,2.276-2.242h0.79c-0.643,1.375-1.316,2.431-2.021,3.169l16.355,0v1.036l-16.355,0c0.52,0.657,0.882,1.147,1.086,1.471c0.206,0.325,0.51,0.891,0.912,1.697H24.294z"/></g></svg>
<a href="#" class="swiper-prev"></a></span>
	      <span class="btn-next">

	<svg version="1.1" class="svg right" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="60px" height="60px" viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve"><g><path d="M35.195,26.268c0.908,0.991,1.694,1.745,2.357,2.261c0.663,0.517,1.289,0.901,1.877,1.154v0.461c-0.677,0.328-1.333,0.747-1.969,1.256c-0.636,0.51-1.395,1.257-2.276,2.241h-0.79c0.643-1.375,1.316-2.431,2.021-3.169H20.06v-1.036h16.355c-0.52-0.656-0.882-1.146-1.087-1.471s-0.51-0.891-0.912-1.697H35.195z"/></g></svg>
<a href="#" class="swiper-next"></a></span>
                        </div>
                    </div>

                </div>

                <div class="swiper-pagination"></div>

            </div>



        </section>








        <nav class="draw-buttons nav three">

            <div class="holder">

					
						
						<span class="btn-prev">
							

	<svg version="1.1" class="svg left" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="60px" height="60px" viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve"><g><path d="M24.294,33.641c-0.908-0.991-1.694-1.745-2.357-2.261c-0.663-0.517-1.289-0.901-1.877-1.154v-0.461c0.677-0.329,1.333-0.748,1.969-1.256c0.635-0.51,1.395-1.257,2.276-2.242h0.79c-0.643,1.375-1.316,2.431-2.021,3.169l16.355,0v1.036l-16.355,0c0.52,0.657,0.882,1.147,1.086,1.471c0.206,0.325,0.51,0.891,0.912,1.697H24.294z"/></g></svg>

							<a href="/collections/all/products/louis-erard" title="">&larr;</a>
						</span>
					

					<span class="btn-close">
						<span class="back">
							

	<svg version="1.1" class="svg close" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="60px" height="60px" viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve"><polygon points="38.936,23.561 36.814,21.439 30.562,27.691 24.311,21.439 22.189,23.561 28.441,29.812   22.189,36.064 24.311,38.186 30.562,31.934 36.814,38.186 38.936,36.064 32.684,29.812 "/></svg>

							<a href="/collections/all"></a>
						</span>
						<span class="front">
							

	<svg version="1.1" class="svg grid" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="60px" height="60px" viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve"><rect x="35.75" y="20" width="5" height="5"/><rect x="27.75" y="20" width="5" height="5"/><rect x="19.75" y="20" width="5" height="5"/><rect x="35.75" y="28" width="5" height="5"/><rect x="27.75" y="28" width="5" height="5"/><rect x="19.75" y="28" width="5" height="5"/><rect x="35.75" y="36" width="5" height="5"/><rect x="27.75" y="36" width="5" height="5"/><rect x="19.75" y="36" width="5" height="5"/></svg>

						</span>
					</span>

					
						
						<span class="btn-next">
							

	<svg version="1.1" class="svg right" xmlns="//www.w3.org  /2000/svg" xmlns:xlink="//www.w3.org  /1999/xlink" x="0px" y="0px" width="60px" height="60px" viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve"><g><path d="M35.195,26.268c0.908,0.991,1.694,1.745,2.357,2.261c0.663,0.517,1.289,0.901,1.877,1.154v0.461c-0.677,0.328-1.333,0.747-1.969,1.256c-0.636,0.51-1.395,1.257-2.276,2.241h-0.79c0.643-1.375,1.316-2.431,2.021-3.169H20.06v-1.036h16.355c-0.52-0.656-0.882-1.146-1.087-1.471s-0.51-0.891-0.912-1.697H35.195z"/></g></svg>

							<a href="/collections/all/products/maple-ipad-sleeve" title="">&rarr;</a>
						</span>


            </div>

        </nav>





    </article>

    <div id="product-page-settings" data-truncated_description="true" data-truncated_description_lines="123" data-gallery_max_size="true" data-gallery_resizing="fill" data-gallery_transition="slide" data-gallery_autoplay="true" data-gallery_timer="6" data-gallery-posfix="false" data-zoom="false"></div>


</div>

