
<!DOCTYPE html>
<!--[if IE]><![endif]-->
<!--[if lt IE 7 ]> <html lang="en" class="ie6">    <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="ie7">    <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="ie8">    <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="ie9">    <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html class="no-js" lang="">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Home || Dilima</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Favicon
		============================================ -->
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.ico">

    <!-- Fonts  -->
    <link href='https://fonts.googleapis.com/css?family=Khula:400,800,700,600,300' rel='stylesheet' type='text/css'>

    <!-- CSS  -->

    <!-- Bootstrap CSS
		============================================ -->
    <link rel="stylesheet" href="css/bootstrap.min.css">

    <!-- owl.carousel CSS
		============================================ -->
    <link rel="stylesheet" href="css/owl.carousel.css">

    <!-- owl.theme CSS
		============================================ -->
    <link rel="stylesheet" href="css/owl.theme.css">

    <!-- owl.transitions CSS
		============================================ -->
    <link rel="stylesheet" href="css/owl.transitions.css">

    <!-- font-awesome.min CSS
		============================================ -->
    <link rel="stylesheet" href="css/font-awesome.min.css">

    <!-- jquery.fancybox CSS
        ============================================ -->
    <link rel="stylesheet" href="css/fancb/jquery.fancybox.css">

    <!-- animate CSS
		============================================ -->
    <link rel="stylesheet" href="css/animate.css">

    <!-- meanmenu CSS
        ============================================ -->
    <link rel="stylesheet" href="css/meanmenu.min.css">

    <!-- normalize CSS
		============================================ -->
    <link rel="stylesheet" href="css/normalize.css">

    <!-- main CSS
		============================================ -->
    <link rel="stylesheet" href="css/main.css">

    <!-- nivo-slider CSS
        ============================================ -->
    <link rel="stylesheet" href="css/nivo-slider.css">

    <!-- style CSS
		============================================ -->
    <link rel="stylesheet" href="style.css">

    <!-- responsive CSS
		============================================ -->
    <link rel="stylesheet" href="css/responsive.css">

    <script src="js/vendor/modernizr-2.8.3.min.js"></script>
</head>
<body class="home-1">
<!--[if lt IE 8]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->
<!-- Start main area -->
<div class="main-area">
    <!-- Start header -->
    <header>
        <!-- Start top call-to acction -->
        <div class="top-bar-area">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-6">
                        <div class="top-call-to-acction">
                            <p>
                                <a href="tel:0123-456-789"><i class="fa fa-phone"></i> Call us now: 0123-456-789</a>
                                <a href="mailto:admin@bootexperts.com"><i class="fa fa-envelope-o"></i> E-mail: admin@bootexperts.com</a>
                            </p>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-6 pull-right">
                        <div class="social-and-menu">
                            <div class="top-menu">
                                <nav>
                                    <ul>
                                        <li><a href="#">English <i class="fa fa-caret-down"></i></a>
                                            <ul>
                                                <li><a href="#">English</a></li>
                                                <li><a href="#">Français</a></li>
                                            </ul>
                                        </li>
                                        <li><a href="#">USD <i class="fa fa-caret-down"></i></a>
                                            <ul>
                                                <li><a href="#">Dollar (USD)</a></li>
                                                <li><a href="#">Pound (GBP)</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                            <div class="top-social">
                                <p>
                                    <a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a>
                                    <a href="https://twitter.com/"><i class="fa fa-twitter"></i></a>
                                    <a href="https://www.rss.com/"><i class="fa fa-rss"></i></a>
                                    <a href="https://www.youtube.com/"><i class="fa fa-youtube"></i></a>
                                    <a href="https://plus.google.com/"><i class="fa fa-google-plus"></i></a>
                                    <a href="https://www.pinterest.com/"><i class="fa fa-pinterest"></i></a>
                                    <a href="www.vimeo.com/‎"><i class="fa fa-vimeo-square"></i></a>
                                    <a href="https://instagram.com/"><i class="fa fa-instagram"></i></a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End top call-to acction -->
        <!-- Start logo and search area -->
        <div class="logo-and-search-area">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-sm-3 col-md-3">
                        <div class="logo">
                            <a href="index.html"><img src="img/logo.png" alt=""></a>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-9 col-md-9">
                        <!-- Start user info adn search -->
                        <div class="user-info-adn-search">
                            <div class="user-info">
                                <p>
                                    <a href="#"><i class="fa fa-user"></i> My Account</a>
                                    <a href="wishlists.html"><i class="fa fa-heart-o"></i> Wishlist</a>
                                    <a href="#"><i class="fa fa-key"></i> Sign out</a>
                                    <a href="#"><i class="fa fa-signal"></i> Compare</a>
                                </p>
                            </div>
                            <div class="search-and-cart">
                                <div class="search-categori">
                                    <div class="categori">
                                        <form id="select-categoris" method="post" class="form-horizontal">
                                            <select name="language">
                                                <option value="">Categories</option>
                                                <option value="12">Automotive</option>
                                                <option value="21">electronic </option>
                                                <option value="25">Camera</option>
                                                <option value="26">Electronic </option>
                                                <option value="27">Cosmetic </option>
                                                <option value="28">Medical</option>
                                                <option value="29">Laptop</option>
                                                <option value="30">Phasellus</option>
                                                <option value="22">mobile</option>
                                                <option value="31">Camcorders </option>
                                                <option value="32">Electronic </option>
                                                <option value="33">Cosmetic </option>
                                                <option value="34">Laptop</option>
                                                <option value="35">Medical</option>
                                                <option value="36">Phasellus</option>
                                                <option value="23">laptop </option>
                                                <option value="37">Phasellus</option>
                                                <option value="38">Healthcare </option>
                                                <option value="39">Electronic </option>
                                                <option value="40">Cosmetic </option>
                                                <option value="13">Electronics </option>
                                                <option value="24">camcorder </option>
                                                <option value="46">Healthcare </option>
                                                <option value="47">Laptop</option>
                                                <option value="48">Camera</option>
                                                <option value="41">Medical</option>
                                                <option value="49">Camera</option>
                                                <option value="50">Camcorders</option>
                                                <option value="51">Camcorders</option>
                                                <option value="42">Healthcare</option>
                                                <option value="52">Medical</option>
                                                <option value="53">Healthcare</option>
                                                <option value="54">Healthcare </option>
                                                <option value="14">Sports</option>
                                                <option value="43">category 1</option>
                                                <option value="60">day </option>
                                                <option value="61">evening </option>
                                                <option value="62">night </option>
                                                <option value="44">category 2 </option>
                                                <option value="63">kids </option>
                                                <option value="64">men </option>
                                                <option value="65">Women </option>
                                                <option value="45">category 3 </option>
                                                <option value="66">clothing </option>
                                                <option value="67">Accessories </option>
                                                <option value="15">Smartphone</option>
                                                <option value="55">category 1 </option>
                                                <option value="56">category 2 </option>
                                                <option value="57">category 3 </option>
                                                <option value="16">Beauty </option>
                                                <option value="58">category 1 </option>
                                                <option value="59">category 2 </option>
                                                <option value="17">Bags, Shoes</option>
                                                <option value="18">Networking </option>
                                                <option value="19">Accessories </option>
                                                <option value="20">Entertainment </option>
                                            </select>
                                        </form>
                                    </div>
                                    <div class="search-box">
                                        <form action="#">
                                            <input type="text" class="form-control input-sm" maxlength="64" placeholder="Enter your search key ... " />
                                            <button type="submit">Search</button>
                                        </form>
                                    </div>
                                </div>
                                <div class="shoping-cart">
                                    <a href="cart.html"><span>My Cart (3)</span></a>
                                    <div class="add-to-cart-product">
                                        <div class="cart-product product-item11">
                                            <div class="cart-product-image">
                                                <a href="single-product.html"><img src="img/cart/faded-short-sleeves-tshirt.jpg" alt="Product"></a>
                                            </div>
                                            <div class="cart-product-info">
                                                <p><span>1</span>x<a href="single-product.html">Faded...</a></p>
                                                <a href="single-product.html">S, Orange</a>
                                                <span class="price">£ 19.81</span>
                                            </div>
                                            <div class="cart-product-remove">
                                                <i class="fa fa-times"></i>
                                            </div>
                                        </div>
                                        <div class="cart-product">
                                            <div class="cart-product-image">
                                                <a href="single-product.html"><img src="img/cart/printed-dress.jpg" alt="Product"></a>
                                            </div>
                                            <div class="cart-product-info">
                                                <p><span>1</span>x<a href="single-product.html">blouse</a></p>
                                                <a href="single-product.html">S, Black</a>
                                                <span class="price">£ 32.40</span>
                                            </div>
                                            <div class="cart-product-remove">
                                                <i class="fa fa-times"></i>
                                            </div>
                                        </div>
                                        <div class="cart-product">
                                            <div class="cart-product-image">
                                                <a href="single-product.html"><img src="img/cart/printed-summer-dress.jpg" alt="Product"></a>
                                            </div>
                                            <div class="cart-product-info">
                                                <p><span>1</span>x<a href="single-product.html">Printed...</a></p>
                                                <a href="single-product.html">S, Yellow</a>
                                                <span class="price">£ 36.60</span>
                                            </div>
                                            <div class="cart-product-remove">
                                                <i class="fa fa-times"></i>
                                            </div>
                                        </div>
                                        <div class="cart-price">
                                            <div class="cart-product-line fast-line">
                                                <span>Shipping</span>
                                                <span class="free-shiping">$10.50</span>
                                            </div>
                                            <div class="cart-product-line">
                                                <span>Total</span>
                                                <span class="total">£ 88.81</span>
                                            </div>
                                        </div>
                                        <div class="cart-checkout">
                                            <a href="checkout.html">Check out<i class="fa fa-chevron-right"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- End user info adn search -->
                    </div>
                </div>
            </div>
        </div>
        <!-- End logo and search area -->
        <?php $this->partial("partials/main_menu"); ?>
    </header>
    <!-- End header -->
    <?php echo $this->getContent(); ?>

    <!-- Start footer -->
    <footer>
        <!-- Start footer top -->
        <div class="footer-top">
            <div class="container">
                <div class="row">
                    <!-- Start footer top box -->
                    <div class="col-xs-12 col-sm-3">
                        <div class="footer-top-box">
                            <i class="fa fa-phone-square"></i>
                            <a href="tel:+-0123-456-789">+ 0(123) 456 789</a>
                            <p>Order by phone</p>
                        </div>
                    </div>
                    <!-- End footer top box -->
                    <!-- Start footer top box -->
                    <div class="col-xs-12 col-sm-3">
                        <div class="footer-top-box">
                            <i class="fa fa-clock-o"></i>
                            <span>Working time</span>
                            <p>Mon - sun: 8.00 - 18.00</p>
                        </div>
                    </div>
                    <!-- End footer top box -->
                    <!-- Start footer top box -->
                    <div class="col-xs-12 col-sm-3">
                        <div class="footer-top-box">
                            <i class="fa fa-paper-plane"></i>
                            <span>Free shipping</span>
                            <p>on order over $199</p>
                        </div>
                    </div>
                    <!-- End footer top box -->
                    <!-- Start footer top box -->
                    <div class="col-xs-12 col-sm-3">
                        <div class="footer-top-box last">
                            <i class="fa fa-history"></i>
                            <span>Money back 100%</span>
                            <p>Within 30 days affter delivery</p>
                        </div>
                    </div>
                    <!-- End footer top box -->
                </div>
            </div>
        </div>
        <!-- End footer top -->
        <!-- Start footer medil -->
        <div class="footer-medil">
            <div class="container">
                <div class="row">
                    <!-- Start footer categori -->
                    <div class="col-xs-12 col-sm-8">
                        <div class="footer-categori">
                            <h4>Categories</h4>
                            <ul>
                                <li><a href="#"><i class="fa fa-star"></i> Automotive & Motorcycle</a></li>
                                <li><a href="#"><i class="fa fa-star"></i> Electronics</a></li>
                                <li><a href="#"><i class="fa fa-star"></i> Sports & Outdoors</a></li>
                                <li><a href="#"><i class="fa fa-star"></i> Smartphone & Tablets</a></li>
                                <li><a href="#"><i class="fa fa-star"></i> Health & Beauty</a></li>
                                <li><a href="#"><i class="fa fa-star"></i> Bags, Shoes & Accessories</a></li>
                                <li><a href="#"><i class="fa fa-star"></i> Computers & Networking</a></li>
                                <li><a href="#"><i class="fa fa-star"></i> Laptops & Accessories</a></li>
                                <li><a href="#"><i class="fa fa-star"></i> Entertainment</a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- End footer categori -->
                    <!-- Start footer search area -->
                    <div class="col-xs-12 col-sm-4">
                        <div class="footer-search-area">
                            <h4>Newsletter</h4>
                            <form method="post" action="#">
                                <div class="form-group">
                                    <button class="submitNew" name="submitNewsletter" type="submit">
                                        <i class="fa fa-envelope"></i>
                                    </button>
                                    <input type="text" value="Enter your e-mail" size="18" name="email" id="newsletter-input" class="inputNew form-control grey newsletter-input">
                                </div>
                            </form>
                            <div class="hiring">
                                <div class="img_in"><img alt="icon" src="img/hire_logo.jpg"></div>
                                <div class="info">
                                    <h4>we’re hiring!</h4>
                                    <p>Click <a href="#">here</a> for more information</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- End footer search area -->
                </div>
                <!-- Start footer medil information -->
                <div class="footer-medil-information">
                    <div class="row">
                        <div class="col-xs-12 col-sm-3">
                            <div class="info-box">
                                <h4>Store Information</h4>
                                <ul>
                                    <li>My Company</li>
                                    <li>Paris - France</li>
                                    <li>0123-456-789</li>
                                    <li><a href="mailto:admin@bootexperts.com">admin@bootexperts.com</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-3">
                            <div class="info-box">
                                <h4>Information</h4>
                                <ul>
                                    <li class="item"><a title="Specials" href="">Specials</a></li>
                                    <li class="item"><a title="New products" href=""> New products</a></li>
                                    <li class="item"><a title="Best sellers" href=""> Best sellers</a></li>
                                    <li class="item"><a title="Contact us" href="contact-us.html">Contact us</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-3">
                            <div class="info-box">
                                <h4><a href="#">My account</a></h4>
                                <ul>
                                    <li class="item"><a title="Specials" href="">My orders</a></li>
                                    <li class="item"><a title="New products" href=""> My credit slips</a></li>
                                    <li class="item"><a title="Best sellers" href=""> My addresses</a></li>
                                    <li class="item"><a title="Contact us" href="">My personal info</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-3">
                            <div class="info-box">
                                <h4>extra link</h4>
                                <ul>
                                    <li class="item"><a title="Specials" href="">gift cards</a></li>
                                    <li class="item"><a title="New products" href="">e- gift cards</a></li>
                                    <li class="item"><a title="Best sellers" href="">corporate gift cards</a></li>
                                    <li class="item"><a title="Contact us" href="">check balance</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End footer medil information -->
            </div>
        </div>
        <!-- End footer medil -->
        <!-- Start footer copyright -->
        <div class="footer-copyright">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-sm-6">
                        <div class="copyright-text">
                            <p>Copyright &copy; 2015 <a href="http://bootexperts.com">BootExperts</a>. All rights reserved.</p>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6">
                        <div class="footer-card pull-right">
                            <img src="img/payment.png" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End footer copyright -->
    </footer>
    <!-- End footer -->
</div>
<!-- End main area -->
<!-- JS -->

<!-- jquery-1.11.3.min js
		============================================ -->
<script src="js/vendor/jquery-1.11.3.min.js"></script>

<!-- bootstrap js
		============================================ -->
<script src="js/bootstrap.min.js"></script>

<!-- owl.carousel.min js
		============================================ -->
<script src="js/owl.carousel.min.js"></script>

<!-- jquery.nivo.slider.pack js
        ============================================ -->
<script src="js/jquery.nivo.slider.pack.js"></script>

<!-- jqueryui js
        ============================================ -->
<script src="js/jquery.fancybox.js"></script>

<!-- jquery.scrollUp.min js
        ============================================ -->
<script src="js/jquery.scrollUp.min.js"></script>

<!-- wow js
		============================================ -->
<script src="js/wow.js"></script>

<!-- jquery.meanmenu js
        ============================================ -->
<script src="js/jquery.meanmenu.js"></script>

<!-- plugins js
		============================================ -->
<script src="js/plugins.js"></script>

<!-- main js
		============================================ -->
<script src="js/main.js"></script>
</body>
</html>
